// Generated by cpp2c (export-headers). DO NOT EDIT.
#include "app_lib.h"

auto triple(cpp2::in<int> n) -> int
{
    return cpp2::checked_mul(static_cast<int>(n), static_cast<int>(3), "tests/cases/exportlib.cppm", 4);
}

