// Generated by cpp2c (export-headers): bridge for Cpp1 consumers.
// DO NOT EDIT.
#pragma once
#include "cpp2/support.hpp"
#include <cmath>
#include <cstdint>
#include <string>
#include <utility>
#include <vector>

#line 6 "tests/cases/exportlib.cppm"
struct Vec {
#line 7 "tests/cases/exportlib.cppm"
    std::vector<int> items = {};
#line 8 "tests/cases/exportlib.cppm"

auto total() const -> int
{
#line 9 "tests/cases/exportlib.cppm"
    int t = 0;
#line 10 "tests/cases/exportlib.cppm"
    for (auto&& v : (items)) {
#line 11 "tests/cases/exportlib.cppm"
        t = cpp2::checked_add(static_cast<int>(t), static_cast<int>(v), "tests/cases/exportlib.cppm", 11);
    }
#line 13 "tests/cases/exportlib.cppm"
    return t;
}
};
#line 4 "tests/cases/exportlib.cppm"
auto triple(cpp2::in<int> n) -> int;
