// C++2 → C++23 发射器实现(M3:摊平 / 模块 / 桥接三种发射模式)
#include "emit.hpp"

#include <unordered_map>
#include <unordered_set>

namespace cpp2::emit {

namespace {

int bin_prec(std::string const& op)
{
    if (op == "||") return 1;
    if (op == "&&") return 2;
    if (op == "==" || op == "!=") return 3;
    if (op == "<" || op == ">" || op == "<=" || op == ">=") return 4;
    if (op == "+" || op == "-") return 5;
    if (op == "*" || op == "/" || op == "%") return 6;
    return 0;
}

int expr_prec(ast::Expr& e)
{
    switch (e.kind()) {
    case ast::Expr::Binary: return bin_prec(static_cast<ast::BinaryExpr&>(e).op);
    case ast::Expr::Unary:  return 7;
    default:                return 8;
    }
}

std::string escape_path(std::string p)
{
    std::string out;
    for (char c : p) {
        if (c == '\\') out += '/';
        else if (c == '"') out += "\\\"";
        else out += c;
    }
    return out;
}

std::string prelude_includes()
{
    return std::string("#include \"cpp2/support.hpp\"\n")
         + "#include <cmath>\n#include <cstdint>\n#include <string>\n"
           "#include <utility>\n#include <vector>\n";
}

// "app.util" → {cpp2mod, app, util}(用于摊平模式的嵌套命名空间与 using)
std::vector<std::string> ns_parts(std::string const& module_name)
{
    std::vector<std::string> parts{"cpp2mod"};
    std::string cur;
    for (char c : module_name) {
        if (c == '.') { if (!cur.empty()) parts.push_back(cur); cur.clear(); }
        else cur += c;
    }
    if (!cur.empty()) parts.push_back(cur);
    return parts;
}

class Emitter {
public:
    Emitter() = default;

    void set(ast::Module& m, sema::Result const& sema, std::string const& src)
    {
        m_ = &m; sema_ = &sema;
        src_ = escape_path(src);
        out_.clear(); indent_ = 0; last_line_ = -1; fresh_ = 0; checks_on_ = true;
    }

    std::string take() { return std::move(out_); }

    // ═══ 模式一:摊平(命名空间块,main 除外)═══════════════════════
    std::string flatten_block()
    {
        auto parts = ns_parts(m_->name);
        out_ += "namespace " + parts[0] + " {\n";
        for (size_t i = 1; i < parts.size(); ++i)
            out_ += "namespace " + parts[i] + " {\n";
        ++indent_;
        decls(/*emit_main*/false, /*exported_visible*/false);
        --indent_;
        for (size_t i = 0; i < parts.size(); ++i) out_ += "}\n";
        return out_;
    }

    // 摊平模式的 using 提升:非 root 只提升导出名;root 提升全部(main 需要见兄弟)
    std::string flatten_usings(bool hoist_all)
    {
        std::string q;
        for (auto& p : ns_parts(m_->name)) q += (q.empty() ? "" : "::") + p;

        std::string s;
        auto hoist = [&](std::string const& n) {
            s += "using " + q + "::" + n + ";\n";
        };
        for (auto& e : m_->enums)   if (e.exported || hoist_all) hoist(e.name);
        for (auto& s2 : m_->structs) if (s2.exported || hoist_all) hoist(s2.name);
        for (auto& g : m_->globals) if (g.exported || hoist_all) hoist(g.name);
        for (auto& f : m_->funcs)   if (f.name != "main") hoist(f.name);
        return s;
    }

    std::string main_definition()
    {
        for (auto& f : m_->funcs)
            if (f.name == "main") { emit_definition(f); return out_; }
        return {};
    }

    // ═══ 模式二:C++20 模块单元 ════════════════════════════════════
    // root(含 main)→ 普通 TU + import 依赖;其余 → export module
    std::string module_unit(ModuleEntry const& e)
    {
        out_ = "// Generated by cpp2c from '" + src_ + "'. DO NOT EDIT.\n";
        if (!e.is_root) {
            out_ += "module;\n" + prelude_includes() + "\n";
            bool any_export = false;
            for (auto& f : m_->funcs)   if (f.exported) any_export = true;
            for (auto& s : m_->structs) if (s.exported) any_export = true;
            for (auto& en : m_->enums)  if (en.exported) any_export = true;
            for (auto& g : m_->globals) if (g.exported) any_export = true;
            out_ += std::string(any_export ? "export module " : "module ") + m_->name + ";\n";
        } else {
            out_ += prelude_includes() + "\n";
        }
        for (auto& imp : e.imports) out_ += "import " + imp + ";\n";
        if (!e.imports.empty()) out_ += "\n";

        // 导出实体(先原型,后定义;root TU 内同 TU 可见)
        for (auto& en : m_->enums)   if (en.exported)  emit_enum(en, e.is_root ? "" : "export ");
        for (auto& s : m_->structs)  if (s.exported)   emit_struct(s, e.is_root ? "" : "export ");
        for (auto& g : m_->globals)  if (g.exported)   emit_global(g, e.is_root ? "" : "export ");

        bool wrote_exported_proto = false;
        for (auto& f : m_->funcs) {
            if (f.name == "main" || !f.exported) continue;
            emit_prototype(f, e.is_root ? "" : "export ");
            wrote_exported_proto = true;
        }
        if (wrote_exported_proto) out_ += "\n";

        // 内部实体 → 匿名命名空间(内部链接;DESIGN §4.7)
        bool has_internal = false;
        for (auto& en : m_->enums)   if (!en.exported) has_internal = true;
        for (auto& s : m_->structs)  if (!s.exported) has_internal = true;
        for (auto& g : m_->globals) if (!g.exported) has_internal = true;
        for (auto& f : m_->funcs)    if (!f.exported && f.name != "main") has_internal = true;
        if (has_internal) {
            out_ += "namespace {\n\n";
            ++indent_;
            for (auto& en : m_->enums)   if (!en.exported) emit_enum(en);
            for (auto& s : m_->structs)  if (!s.exported) emit_struct(s);
            for (auto& g : m_->globals) if (!g.exported) emit_global(g);
            for (auto& f : m_->funcs)    if (!f.exported && f.name != "main") emit_prototype(f);
            out_ += "\n";
            for (auto& f : m_->funcs)    if (!f.exported && f.name != "main") emit_definition(f);
            --indent_;
            out_ += "} // namespace\n\n";
        }

        // 导出函数定义(重新声明不带 export;匿名内部已可见)
        for (auto& f : m_->funcs) {
            if (f.name == "main" || !f.exported) continue;
            emit_definition(f);
        }
        if (e.is_root) {
            for (auto& f : m_->funcs)
                if (f.name == "main") emit_definition(f);
        }
        return out_;
    }

    // ═══ 模式三:桥接(.h 声明 / .cpp 定义)════════════════════════
    std::string bridge_header(std::string const& libname)
    {
        out_ = "// Generated by cpp2c (export-headers): bridge for Cpp1 consumers.\n"
               "// DO NOT EDIT.\n#pragma once\n";
        out_ += prelude_includes() + "\n";
        for (auto& en : m_->enums)   if (en.exported) emit_enum(en);
        for (auto& s : m_->structs)  if (s.exported) emit_struct(s);
        for (auto& g : m_->globals)  if (g.exported) {
            sync_line(g.line);
            out_ += "extern " + type_str(g.type) + " " + g.name + ";\n";
        }
        for (auto& f : m_->funcs) {
            if (!f.exported || f.name == "main") continue;
            emit_prototype(f);
        }
        (void)libname;
        return out_;
    }

    std::string bridge_impl(std::string const& libname)
    {
        out_ = "// Generated by cpp2c (export-headers). DO NOT EDIT.\n";
        out_ += "#include \"" + libname + ".h\"\n\n";

        // 内部实体:匿名命名空间(限制:导出函数体不得引用跨模块内部名)
        bool has_internal = false;
        for (auto& en : m_->enums)   if (!en.exported) has_internal = true;
        for (auto& s : m_->structs)  if (!s.exported) has_internal = true;
        for (auto& g : m_->globals) if (!g.exported) has_internal = true;
        for (auto& f : m_->funcs)    if (!f.exported && f.name != "main") has_internal = true;
        if (has_internal) {
            out_ += "namespace {\n\n";
            ++indent_;
            for (auto& en : m_->enums)   if (!en.exported) emit_enum(en);
            for (auto& s : m_->structs)  if (!s.exported) emit_struct(s);
            for (auto& g : m_->globals) if (!g.exported) emit_global(g);
            for (auto& f : m_->funcs)    if (!f.exported && f.name != "main") emit_prototype(f);
            out_ += "\n";
            for (auto& f : m_->funcs)    if (!f.exported && f.name != "main") emit_definition(f);
            --indent_;
            out_ += "} // namespace\n\n";
        }

        for (auto& g : m_->globals) if (g.exported) emit_global(g);
        for (auto& f : m_->funcs) {
            if (!f.exported || f.name == "main") continue;
            emit_definition(f);
        }
        return out_;
    }

private:
    ast::Module* m_ = nullptr;
    sema::Result const* sema_ = nullptr;
    std::string src_;
    std::string out_;
    int indent_ = 0;
    int last_line_ = -1;
    int fresh_ = 0;
    bool checks_on_ = true;
    // post 契约发射状态:old(...) → 入口缓存变量;result → __c2_result
    // (throws 函数包 expected 需解引用;普通函数直接引用)
    std::unordered_map<ast::Expr*, std::string> const* old_names_ = nullptr;
    bool in_post_ = false;
    bool result_wrapped_ = false;

    sema::Type type_of(ast::Expr& e) const { return sema_->type_of(e); }

    // ── 声明序列(命名空间/匿名块内部通用;main 除外)──────────────
    void decls(bool emit_main, bool)
    {
        for (auto& e : m_->enums)   emit_enum(e);
        for (auto& s : m_->structs) emit_struct(s);
        for (auto& g : m_->globals) emit_global(g);
        for (auto& f : m_->funcs)   if (f.name != "main") emit_prototype(f);
        out_ += "\n";
        for (auto& f : m_->funcs) {
            if (f.name == "main" && !emit_main) continue;
            emit_definition(f);
        }
    }

    // ── 类型与名字映射(IMPL §4.7 stdbridge)───────────────────────
    static std::string map_type_name(std::string const& n)
    {
        static std::unordered_map<std::string, std::string> const map{
            {"int", "int"}, {"double", "double"}, {"float", "float"},
            {"bool", "bool"}, {"void", "void"}, {"char", "char"},
            {"i8", "std::int8_t"}, {"i16", "std::int16_t"},
            {"i32", "std::int32_t"}, {"i64", "std::int64_t"},
            {"u8", "std::uint8_t"}, {"u16", "std::uint16_t"},
            {"u32", "std::uint32_t"}, {"u64", "std::uint64_t"},
            {"string", "std::string"}, {"string_view", "std::string_view"},
            {"list", "std::vector"}, {"vector", "std::vector"},
            {"byte", "std::byte"},
            {"unique", "std::unique_ptr"}, {"shared", "std::shared_ptr"},
            {"weak", "std::weak_ptr"},
        };
        auto it = map.find(n);
        return it != map.end() ? it->second : n;
    }

    std::string type_str(ast::TypeUse const& t)
    {
        if (t.parts.empty()) return "void";
        std::string s = map_type_name(t.parts[0]);
        for (size_t i = 1; i < t.parts.size(); ++i) s += "::" + t.parts[i];
        if (!t.args.empty()) {
            s += "<";
            for (size_t i = 0; i < t.args.size(); ++i) {
                if (i) s += ", ";
                s += type_str(t.args[i]);
            }
            s += ">";
        }
        if (t.is_const) s += " const";
        return s;
    }

    std::string name_expr_str(ast::NameExpr& n)
    {
        if (n.parts.size() == 2 && n.parts[0] == "std") {
            if (n.parts[1] == "print" || n.parts[1] == "println")
                return "cpp2::stdx::" + n.parts[1];
            return "std::" + n.parts[1];
        }
        if (n.parts.size() == 1
            && (n.parts[0] == "make_unique" || n.parts[0] == "make_shared"))
            return "cpp2::" + n.parts[0];
        std::string s = n.parts[0];
        for (size_t i = 1; i < n.parts.size(); ++i) s += "::" + n.parts[i];
        return s;
    }

    std::string check_loc(int line) const
    {
        return ", \"" + src_ + "\", " + std::to_string(line);
    }

    static std::string cpp_type_of(sema::Type const& t)
    {
        switch (t.kind) {
        case sema::Type::Int:  return "int";
        case sema::Type::I8:   return "std::int8_t";
        case sema::Type::I16:  return "std::int16_t";
        case sema::Type::I32:  return "std::int32_t";
        case sema::Type::I64:  return "std::int64_t";
        case sema::Type::U8:   return "std::uint8_t";
        case sema::Type::U16:  return "std::uint16_t";
        case sema::Type::U32:  return "std::uint32_t";
        case sema::Type::U64:  return "std::uint64_t";
        default:               return "int";
        }
    }

    std::string checked_call(std::string const& fn, ast::Expr& l, ast::Expr& r,
                             sema::Type const& res, int line)
    {
        std::string t = cpp_type_of(res);
        return "cpp2::" + fn + "(static_cast<" + t + ">(" + expr(l)
             + "), static_cast<" + t + ">(" + expr(r) + ")" + check_loc(line) + ")";
    }

    // ── 表达式 ─────────────────────────────────────────────────────
    std::string expr(ast::Expr& e)
    {
        switch (e.kind()) {
        case ast::Expr::Literal:
            return static_cast<ast::LiteralExpr&>(e).text;
        case ast::Expr::Name: {
            auto& n = static_cast<ast::NameExpr&>(e);
            if (in_post_ && n.parts.size() == 1 && n.parts[0] == "result")
                return result_wrapped_ ? "(*__c2_result)" : "__c2_result";
            return name_expr_str(n);
        }
        case ast::Expr::Paren:
            return "(" + expr(*static_cast<ast::ParenExpr&>(e).inner) + ")";
        case ast::Expr::Call: {
            auto& c = static_cast<ast::CallExpr&>(e);
            // post 契约中的 old(...) → 入口缓存变量(sema 保证仅 post 出现)
            if (old_names_) {
                auto it = old_names_->find(&c);
                if (it != old_names_->end()) return it->second;
            }
            // err("msg") → cpp2::err("msg", "file", line)(sema 已标 ErrVal)
            if (c.callee->kind() == ast::Expr::Name && c.args.size() == 1
                && type_of(c).kind == sema::Type::ErrVal) {
                auto& name = static_cast<ast::NameExpr&>(*c.callee);
                if (name.parts.size() == 1 && name.parts[0] == "err")
                    return "cpp2::err(" + expr(*c.args[0]) + check_loc(c.line) + ")";
            }
            std::string s = expr(*c.callee) + "(";
            for (size_t i = 0; i < c.args.size(); ++i) {
                if (i) s += ", ";
                s += expr(*c.args[i]);
            }
            return s + ")";
        }
        case ast::Expr::Binary: {
            auto& b = static_cast<ast::BinaryExpr&>(e);
            if (checks_on_ && (b.op == "+" || b.op == "-" || b.op == "*"
                            || b.op == "/" || b.op == "%")) {
                sema::Type l = type_of(*b.lhs), r = type_of(*b.rhs);
                if (l.is_signed() && r.is_signed()) {
                    std::string fn = b.op == "+" ? "checked_add"
                                  : b.op == "-" ? "checked_sub"
                                  : b.op == "*" ? "checked_mul"
                                  : b.op == "/" ? "checked_div"
                                                : "checked_mod";
                    return checked_call(fn, *b.lhs, *b.rhs, type_of(b), b.line);
                }
            }
            int p = bin_prec(b.op);
            std::string l = expr(*b.lhs);
            std::string r = expr(*b.rhs);
            if (expr_prec(*b.lhs) < p) l = "(" + l + ")";
            if (expr_prec(*b.rhs) <= p && b.rhs->kind() == ast::Expr::Binary) r = "(" + r + ")";
            return l + " " + b.op + " " + r;
        }
        case ast::Expr::Unary: {
            auto& u = static_cast<ast::UnaryExpr&>(e);
            if (u.op == "move")
                return "std::move(" + expr(*u.operand) + ")";
            std::string s = expr(*u.operand);
            if (expr_prec(*u.operand) < 7) s = "(" + s + ")";
            return u.op + s;
        }
        case ast::Expr::Assign: {
            auto& a = static_cast<ast::AssignExpr&>(e);
            return expr(*a.target) + " " + a.op + " " + expr(*a.value);
        }
        case ast::Expr::Index: {
            auto& x = static_cast<ast::IndexExpr&>(e);
            sema::Type b = type_of(*x.base);
            if (checks_on_ && b.is_indexable()) {
                return "cpp2::index(" + expr(*x.base) + ", " + expr(*x.index)
                     + check_loc(x.line) + ")";
            }
            std::string s = expr(*x.base);
            if (expr_prec(*x.base) < 8) s = "(" + s + ")";
            return s + "[" + expr(*x.index) + "]";
        }
        case ast::Expr::Member: {
            auto& x = static_cast<ast::MemberExpr&>(e);
            sema::Type b = type_of(*x.base);
            std::string s = expr(*x.base);
            if (expr_prec(*x.base) < 8) s = "(" + s + ")";
            if (b.is_smart()) {
                // '.' 自动解引用经空检查(DESIGN §6.4):deref(p)->member
                if (checks_on_)
                    return "cpp2::deref(" + s + check_loc(x.line) + ")->" + x.name;
                return s + "->" + x.name;
            }
            return s + "." + x.name;
        }
        case ast::Expr::StructLit: {
            auto& l = static_cast<ast::StructLitExpr&>(e);
            std::string name = map_type_name(l.type_parts[0]);
            for (size_t i = 1; i < l.type_parts.size(); ++i) name += "::" + l.type_parts[i];

            std::vector<std::pair<std::string, ast::Expr*>> ordered;
            if (l.type_parts.size() == 1) {
                if (auto* sd = m_->find_struct(l.type_parts[0])) {
                    for (auto* f : fields_of(*sd)) {
                        for (auto& [fn, fv] : l.fields)
                            if (fn == f->name) ordered.push_back({fn, fv.get()});
                    }
                }
            }
            if (ordered.empty())
                for (auto& [fn, fv] : l.fields) ordered.push_back({fn, fv.get()});

            std::string s = name + "{";
            for (size_t i = 0; i < ordered.size(); ++i) {
                if (i) s += ", ";
                s += "." + ordered[i].first + " = " + expr(*ordered[i].second);
            }
            return s + "}";
        }
        case ast::Expr::AsCast: {
            auto& x = static_cast<ast::AsCastExpr&>(e);
            sema::Type src = type_of(*x.operand);
            sema::Type dst = type_from_target(x.target);
            std::string inner = expr(*x.operand);
            if (expr_prec(*x.operand) < 8) inner = "(" + inner + ")";
            std::string t = type_str(x.target);
            if (checks_on_ && src.is_arith() && dst.is_arith())
                return "cpp2::narrow_cast<" + t + ">(" + inner + check_loc(x.line) + ")";
            return "static_cast<" + t + ">(" + inner + ")";
        }
        case ast::Expr::ListLit: {
            auto& l = static_cast<ast::ListLitExpr&>(e);
            if (l.elements.empty()) return "{}";   // 声明侧已定型:list<int> v = {}
            std::string s = "std::vector{";
            for (size_t i = 0; i < l.elements.size(); ++i) {
                if (i) s += ", ";
                s += expr(*l.elements[i]);
            }
            return s + "}";
        }
        case ast::Expr::Must: {
            // f()! → cpp2::must(f(), "file", line);失败即 bug → trap(DESIGN §8.2)
            auto& x = static_cast<ast::MustExpr&>(e);
            return "(cpp2::must(" + expr(*x.operand) + check_loc(x.line) + "))";
        }
        case ast::Expr::OrDefault: {
            // f() or "d" → (f()).value_or("d")(DESIGN §8.3)
            auto& x = static_cast<ast::OrDefaultExpr&>(e);
            return "(" + expr(*x.lhs) + ").value_or((" + expr(*x.rhs) + "))";
        }
        case ast::Expr::Try:
            // '?' 的机械展开需要语句级拆分,由 emit_stmt 处理;
            // 走到这里说明 sema 漏检——发射防御性标记,生成码编译期暴露
            return "/*internal:'?' outside statement position*/ ("
                 + expr(*static_cast<ast::TryExpr&>(e).operand) + ")";
        }
        return "/*?*/";
    }

    sema::Type type_from_target(ast::TypeUse const& tu)
    {
        std::string n = tu.parts.empty() ? "" : tu.parts.back();
        sema::Type t;
        if (n == "int" || n == "i8" || n == "i16" || n == "i32" || n == "i64"
         || n == "int32_t" || n == "int64_t") t.kind = sema::Type::Int;
        else if (n == "u8" || n == "u16" || n == "u32" || n == "u64"
              || n == "uint32_t" || n == "uint64_t") t.kind = sema::Type::U32;
        else if (n == "double" || n == "float") t.kind = sema::Type::Double;
        else if (n == "bool") t.kind = sema::Type::Bool;
        else if (n == "char") t.kind = sema::Type::Char;
        return t;
    }

    std::vector<ast::FieldDecl*> fields_of(ast::StructDecl& s)
    {
        std::vector<ast::FieldDecl*> out;
        if (s.base && s.base->parts.size() == 1)
            if (auto* b = m_->find_struct(s.base->parts[0])) {
                auto base_fields = fields_of(*b);
                out.insert(out.end(), base_fields.begin(), base_fields.end());
            }
        for (auto& f : s.fields) out.push_back(&f);
        return out;
    }

    // ── 语句 ───────────────────────────────────────────────────────
    std::string pad() const { return std::string(indent_ * 4, ' '); }

    void sync_line(int line)
    {
        if (line > 0 && line != last_line_) {
            out_ += "#line " + std::to_string(line) + " \"" + src_ + "\"\n";
            last_line_ = line;
        }
    }

    void emit_body(ast::Stmt& s)
    {
        if (s.kind() == ast::Stmt::Block) {
            for (auto& st : static_cast<ast::BlockStmt&>(s).stmts) emit_stmt(*st);
        } else {
            emit_stmt(s);
        }
    }

    void emit_stmt(ast::Stmt& s)
    {
        bool prev_checks = checks_on_;
        checks_on_ = checks_on_ && !s.no_check;

        switch (s.kind()) {
        case ast::Stmt::ExprStmt: {
            auto& x = static_cast<ast::ExprStmt&>(s);
            if (x.expr->kind() == ast::Expr::Try) {
                // 裸 f()?;:检查 + 传播,丢弃值(expected<void> 风格的调用点)
                sync_line(s.line);
                emit_try_core(static_cast<ast::TryExpr&>(*x.expr));
                break;
            }
            if (x.expr->kind() == ast::Expr::Assign) {
                auto& a = static_cast<ast::AssignExpr&>(*x.expr);
                sync_line(s.line);
                if (a.value->kind() == ast::Expr::Try && a.op == "=") {
                    // x = f()?;:右值机械展开(临时量作用域隔离)
                    out_ += pad() + "{\n";
                    ++indent_;
                    std::string tmp = emit_try_core(static_cast<ast::TryExpr&>(*a.value));
                    out_ += pad() + expr(*a.target) + " = *std::move(" + tmp + ");\n";
                    --indent_;
                    out_ += pad() + "}\n";
                    break;
                }
                if (a.op != "=" && checks_on_) {
                    sema::Type t = type_of(*a.target);
                    if (t.is_signed()) {
                        std::string fn = a.op == "+=" ? "checked_add"
                                       : a.op == "-=" ? "checked_sub"
                                       : a.op == "*=" ? "checked_mul"
                                       : a.op == "/=" ? "checked_div"
                                                      : "checked_mod";
                        std::string target = expr(*a.target);
                        out_ += pad() + target + " = "
                              + checked_call(fn, *a.target, *a.value, t, a.line) + ";\n";
                        break;
                    }
                }
                out_ += pad() + expr(*x.expr) + ";\n";
            } else {
                sync_line(s.line);
                out_ += pad() + "(void)(" + expr(*x.expr) + ");\n";
            }
            break;
        }
        case ast::Stmt::Return: {
            auto& r = static_cast<ast::ReturnStmt&>(s);
            sync_line(s.line);
            if (r.value && r.value->kind() == ast::Expr::Try) {
                // return f()?;:失败提前 return unexpected,成功解包
                std::string tmp = emit_try_core(static_cast<ast::TryExpr&>(*r.value));
                out_ += pad() + "return *std::move(" + tmp + ");\n";
                break;
            }
            out_ += pad() + (r.value ? "return " + expr(*r.value) + ";\n" : "return;\n");
            break;
        }
        case ast::Stmt::Var: {
            auto& v = static_cast<ast::VarStmt&>(s);
            sync_line(v.line);
            std::string type = v.has_type ? type_str(v.type)
                              : (v.is_const ? "auto const" : "auto");
            if (v.init && v.init->kind() == ast::Expr::Try) {
                // x := f()?; 机械展开(IMPL §4.3):求值 → 失败传播 → 解包绑定
                std::string tmp = emit_try_core(static_cast<ast::TryExpr&>(*v.init));
                out_ += pad() + type + " " + v.name + " = *std::move(" + tmp + ");\n";
                break;
            }
            out_ += pad() + type + " " + v.name + " = " + expr(*v.init) + ";\n";
            break;
        }
        case ast::Stmt::If: {
            auto& i = static_cast<ast::IfStmt&>(s);
            sync_line(s.line);
            if (i.is_let()) {
                emit_if_let(i);
                break;
            }
            out_ += pad() + "if (" + expr(*i.cond) + ") {\n";
            ++indent_;
            emit_body(*i.then_block);
            --indent_;
            if (i.else_block) {
                out_ += pad() + "} else ";
                if (i.else_block->kind() == ast::Stmt::If)
                    emit_if_inline(static_cast<ast::IfStmt&>(*i.else_block));
                else {
                    out_ += "{\n";
                    ++indent_;
                    emit_body(*i.else_block);
                    --indent_;
                    out_ += pad() + "}\n";
                }
            } else {
                out_ += pad() + "}\n";
            }
            break;
        }
        case ast::Stmt::While: {
            auto& w = static_cast<ast::WhileStmt&>(s);
            sync_line(s.line);
            out_ += pad() + "while (" + expr(*w.cond) + ") {\n";
            ++indent_;
            emit_body(*w.body);
            --indent_;
            out_ += pad() + "}\n";
            break;
        }
        case ast::Stmt::For:
            emit_for(static_cast<ast::ForStmt&>(s));
            break;
        case ast::Stmt::Break:    sync_line(s.line); out_ += pad() + "break;\n"; break;
        case ast::Stmt::Continue: sync_line(s.line); out_ += pad() + "continue;\n"; break;
        case ast::Stmt::Block: {
            auto& b = static_cast<ast::BlockStmt&>(s);
            sync_line(s.line);
            out_ += pad() + "{\n";
            ++indent_;
            for (auto& st : b.stmts) emit_stmt(*st);
            --indent_;
            out_ += pad() + "}\n";
            break;
        }
        case ast::Stmt::Match:
            emit_match(static_cast<ast::MatchStmt&>(s));
            break;
        }

        checks_on_ = prev_checks;
    }

    // '?' 核心展开:求值到临时量,失败提前 return unexpected;返回临时量名。
    // 解包/绑定/丢弃由调用侧追加(变量初始化 / return / 赋值 / 裸语句)。
    std::string emit_try_core(ast::TryExpr& t)
    {
        std::string tmp = "__c2_try_" + std::to_string(fresh_++);
        out_ += pad() + "auto " + tmp + " = (" + expr(*t.operand) + ");\n";
        out_ += pad() + "if (!" + tmp + ") { return std::unexpected(std::move("
              + tmp + ").error()); }\n";
        return tmp;
    }

    // if x := f() { } else e := it { }:has_value 分支 + 错误绑定(DESIGN §8.3)
    void emit_if_let(ast::IfStmt& i)
    {
        std::string tmp = "__c2_if_" + std::to_string(fresh_++);
        out_ += pad() + "{\n";
        ++indent_;
        out_ += pad() + "auto&& " + tmp + " = (" + expr(*i.let_init) + ");\n";
        out_ += pad() + "if (" + tmp + ".has_value()) {\n";
        ++indent_;
        if (i.let_name != "_")
            out_ += pad() + "auto&& " + i.let_name + " = *" + tmp + ";\n";
        emit_body(*i.then_block);
        --indent_;
        if (i.else_block) {
            out_ += pad() + "} else {\n";
            ++indent_;
            if (!i.else_binding.empty())
                out_ += pad() + "auto&& " + i.else_binding + " = " + tmp + ".error();\n";
            emit_body(*i.else_block);
            --indent_;
        }
        out_ += pad() + "}\n";
        --indent_;
        out_ += pad() + "}\n";
    }

    // match f() { ok x => ...; err e => ...; }:has_value() 分支链(M2c 两臂)
    void emit_match(ast::MatchStmt& x)
    {
        std::string tmp = "__c2_m_" + std::to_string(fresh_++);
        out_ += pad() + "{\n";
        ++indent_;
        out_ += pad() + "auto&& " + tmp + " = (" + expr(*x.scrutinee) + ");\n";
        for (size_t k = 0; k < x.arms.size(); ++k) {
            auto& arm = x.arms[k];
            std::string cond = arm.is_ok ? tmp + ".has_value()"
                                         : "!" + tmp + ".has_value()";
            if (k == 0)                      out_ += pad() + "if (" + cond + ") {\n";
            else if (k + 1 < x.arms.size())  out_ += pad() + "} else if (" + cond + ") {\n";
            else                             out_ += pad() + "} else {\n";
            ++indent_;
            if (arm.binding != "_")
                out_ += pad() + "auto&& " + arm.binding + " = "
                      + (arm.is_ok ? "*" + tmp : tmp + ".error()") + ";\n";
            emit_body(*arm.body);
            --indent_;
        }
        out_ += pad() + "}\n";
        --indent_;
        out_ += pad() + "}\n";
    }

    void emit_if_inline(ast::IfStmt& i)
    {
        out_ += "if (" + expr(*i.cond) + ") {\n";
        ++indent_;
        emit_body(*i.then_block);
        --indent_;
        if (i.else_block) {
            out_ += pad() + "} else ";
            if (i.else_block->kind() == ast::Stmt::If)
                emit_if_inline(static_cast<ast::IfStmt&>(*i.else_block));
            else {
                out_ += "{\n";
                ++indent_;
                emit_body(*i.else_block);
                --indent_;
                out_ += pad() + "}\n";
            }
        } else {
            out_ += pad() + "}\n";
        }
    }

    void emit_for(ast::ForStmt& f)
    {
        sync_line(f.line);
        if (f.is_range) {
            std::string end_name = "__cpp2_end_" + std::to_string(fresh_++);
            out_ += pad() + "{\n";
            ++indent_;
            out_ += pad() + "auto&& " + end_name + " = (" + expr(*f.range_end) + ");\n";
            out_ += pad() + "for (auto " + f.var + " = (" + expr(*f.range_begin) + "); "
                  + f.var + (f.inclusive ? " <= " : " < ") + end_name
                  + "; ++" + f.var + ") {\n";
            ++indent_;
            emit_body(*f.body);
            --indent_;
            out_ += pad() + "}\n";
            --indent_;
            out_ += pad() + "}\n";
        } else {
            out_ += pad() + "for (auto&& " + f.var + " : (" + expr(*f.iterable) + ")) {\n";
            ++indent_;
            emit_body(*f.body);
            --indent_;
            out_ += pad() + "}\n";
        }
    }

    // ── 声明 ───────────────────────────────────────────────────────
    std::string param_str(ast::Param const& p, bool with_default)
    {
        std::string res;
        switch (p.mode) {
        case ast::ParamMode::In:      res = "cpp2::in<" + type_str(p.type) + "> " + p.name; break;
        case ast::ParamMode::Inout:
        case ast::ParamMode::Out:     res = type_str(p.type) + "& " + p.name; break;
        case ast::ParamMode::Move:    res = type_str(p.type) + "&& " + p.name; break;
        case ast::ParamMode::Copy:    res = type_str(p.type) + " " + p.name; break;
        case ast::ParamMode::Forward: res = std::string("auto&& ") + p.name; break;
        }
        if (with_default && p.default_value) res += " = " + expr(*p.default_value);
        return res;
    }

    std::string params_str(std::vector<ast::Param> const& ps, bool with_defaults)
    {
        std::string s;
        for (size_t i = 0; i < ps.size(); ++i) {
            if (i) s += ", ";
            s += param_str(ps[i], with_defaults);
        }
        return s;
    }

    // throws → cpp2::expected<R>(= std::expected<R, cpp2::error>,IMPL §4.3)
    std::string ret_type_str(std::optional<ast::TypeUse> const& ret, bool throws)
    {
        std::string rt = ret ? type_str(*ret) : "void";
        if (throws) rt = "cpp2::expected<" + rt + ">";
        return rt;
    }

    std::string signature(ast::FuncDecl& f, bool with_defaults)
    {
        std::string s;
        if (f.name == "main") s = "int main(";
        else                  s = "auto " + f.name + "(";
        s += params_str(f.params, with_defaults) + ")";
        if (f.name != "main" && f.ret)
            s += " -> " + ret_type_str(f.ret, f.throws);
        return s;
    }

    // 收集 post 契约中的 old(...) 节点 → 缓存变量名(发射顺序 = 遍历顺序,稳定)
    void collect_olds(ast::Expr& e, std::unordered_map<ast::Expr*, std::string>& out)
    {
        switch (e.kind()) {
        case ast::Expr::Literal:
        case ast::Expr::Name:
            return;
        case ast::Expr::Paren:
            return collect_olds(*static_cast<ast::ParenExpr&>(e).inner, out);
        case ast::Expr::Call: {
            auto& c = static_cast<ast::CallExpr&>(e);
            if (c.callee->kind() == ast::Expr::Name
                && static_cast<ast::NameExpr&>(*c.callee).parts.size() == 1
                && static_cast<ast::NameExpr&>(*c.callee).parts[0] == "old"
                && c.args.size() == 1) {
                out.emplace(&e, "__c2_old_" + std::to_string(fresh_++));
            }
            for (auto& a : c.args) collect_olds(*a, out);
            return;
        }
        case ast::Expr::Binary: {
            auto& b = static_cast<ast::BinaryExpr&>(e);
            collect_olds(*b.lhs, out);
            collect_olds(*b.rhs, out);
            return;
        }
        case ast::Expr::Unary:
            return collect_olds(*static_cast<ast::UnaryExpr&>(e).operand, out);
        case ast::Expr::Assign: {
            auto& a = static_cast<ast::AssignExpr&>(e);
            collect_olds(*a.target, out);
            collect_olds(*a.value, out);
            return;
        }
        case ast::Expr::Index: {
            auto& x = static_cast<ast::IndexExpr&>(e);
            collect_olds(*x.base, out);
            collect_olds(*x.index, out);
            return;
        }
        case ast::Expr::Member:
            return collect_olds(*static_cast<ast::MemberExpr&>(e).base, out);
        case ast::Expr::StructLit: {
            for (auto& [n, v] : static_cast<ast::StructLitExpr&>(e).fields)
                collect_olds(*v, out);
            return;
        }
        case ast::Expr::AsCast:
            return collect_olds(*static_cast<ast::AsCastExpr&>(e).operand, out);
        case ast::Expr::ListLit: {
            for (auto& el : static_cast<ast::ListLitExpr&>(e).elements)
                collect_olds(*el, out);
            return;
        }
        case ast::Expr::Try:
            return collect_olds(*static_cast<ast::TryExpr&>(e).operand, out);
        case ast::Expr::OrDefault: {
            auto& x = static_cast<ast::OrDefaultExpr&>(e);
            collect_olds(*x.lhs, out);
            collect_olds(*x.rhs, out);
            return;
        }
        case ast::Expr::Must:
            return collect_olds(*static_cast<ast::MustExpr&>(e).operand, out);
        }
    }

    // 函数体发射:无契约 = 原样;有契约 = old 入口缓存 → pre → 体(post 时
    // lambda 包裹)→ post 检查(DESIGN §6.5,IMPL §4.4)。
    // throws 函数的 lambda 返回 expected('?'/return R 同型直达出口);
    // 非 throws 函数返回 R 本身——失败只可能来自 trap,不存在错误传播。
    void emit_body_of(std::string const& name, bool throws, ast::Expr* pre, ast::Expr* post,
                      bool has_block, ast::Stmt* block, ast::Expr* body_expr,
                      std::optional<ast::TypeUse> const& ret, int line)
    {
        ++indent_;
        bool returns = ret.has_value() && type_str(*ret) != "void";

        if (!pre && !post) {                   // 快路径:零额外代码
            emit_body_core(has_block, block, body_expr, ret, line);
            --indent_;
            return;
        }

        // old() 入口缓存(post 中的 old(expr) 在函数入口求值并暂存)
        std::unordered_map<ast::Expr*, std::string> olds;
        if (post) collect_olds(*post, olds);
        for (auto& [call, var] : olds) {
            auto& oc = static_cast<ast::CallExpr&>(*call);
            sync_line(oc.line);
            out_ += pad() + "auto " + var + " = (" + expr(*oc.args[0]) + ");\n";
        }

        if (pre) {                             // pre:违反 = bug → trap,不可捕获
            sync_line(pre->line);
            out_ += pad() + "if (!(" + expr(*pre) + ")) { cpp2::trap(\"precondition failed: "
                  + name + "\"" + check_loc(pre->line) + "); }\n";
        }

        if (!post) {
            emit_body_core(has_block, block, body_expr, ret, line);
            --indent_;
            return;
        }

        if (returns) {
            // 体包进 lambda:return R 隐式转 expected;'?' 传播同型直达出口
            std::string lt = throws ? "cpp2::expected<" + type_str(*ret) + ">"
                                    : type_str(*ret);
            out_ += pad() + "auto __c2_result = [&]() -> " + lt + " {\n";
            ++indent_;
            emit_body_core(has_block, block, body_expr, ret, line);
            --indent_;
            out_ += pad() + "}();\n";
            if (throws)
                out_ += pad() + "if (!__c2_result) { return __c2_result; }\n";
            old_names_ = &olds;
            in_post_ = true;
            result_wrapped_ = throws;
            sync_line(post->line);
            out_ += pad() + "if (!(" + expr(*post) + ")) { cpp2::trap(\"postcondition failed: "
                  + name + "\"" + check_loc(post->line) + "); }\n";
            in_post_ = false;
            old_names_ = nullptr;
            out_ += pad() + "return __c2_result;\n";
        } else {
            out_ += pad() + "[&] {\n";
            ++indent_;
            emit_body_core(has_block, block, body_expr, ret, line);
            --indent_;
            out_ += pad() + "}();\n";
            old_names_ = &olds;
            in_post_ = true;
            sync_line(post->line);
            out_ += pad() + "if (!(" + expr(*post) + ")) { cpp2::trap(\"postcondition failed: "
                  + name + "\"" + check_loc(post->line) + "); }\n";
            in_post_ = false;
            old_names_ = nullptr;
        }
        --indent_;
    }

    void emit_body_core(bool has_block, ast::Stmt* block, ast::Expr* body_expr,
                        std::optional<ast::TypeUse> const& ret, int line)
    {
        if (has_block && block) {
            emit_body(*block);
        } else if (body_expr) {
            bool returns = ret.has_value() && type_str(*ret) != "void";
            sync_line(line);
            out_ += pad() + (returns ? "return " : "(void)(")
                  + expr(*body_expr) + (returns ? ";\n" : ");\n");
        }
    }

    void emit_prototype(ast::FuncDecl& f, std::string const& prefix = "")
    {
        sync_line(f.line);
        out_ += prefix + signature(f, /*with_defaults*/true) + ";\n";
    }

    void emit_definition(ast::FuncDecl& f)
    {
        sync_line(f.line);
        out_ += signature(f, /*with_defaults*/false) + "\n{\n";
        emit_body_of(f.name, f.throws, f.pre.get(), f.post.get(),
                     f.has_block_body, f.block_body.get(), f.expr_body.get(), f.ret, f.line);
        out_ += "}\n\n";
    }

    void emit_global(ast::GlobalVar& g, std::string const& prefix = "")
    {
        sync_line(g.line);
        std::string type = g.has_type ? type_str(g.type)
                          : (g.is_const ? "auto const" : "auto");
        out_ += prefix + type + " " + g.name
              + (g.init ? " = " + expr(*g.init) : "") + ";\n";
    }

    void emit_enum(ast::EnumDecl& e, std::string const& prefix = "")
    {
        sync_line(e.line);
        out_ += prefix + "enum class " + e.name;
        if (e.underlying) out_ += " : " + type_str(*e.underlying);
        out_ += " { ";
        for (size_t i = 0; i < e.members.size(); ++i) {
            if (i) out_ += ", ";
            out_ += e.members[i];
        }
        out_ += " };\n";
    }

    void emit_struct(ast::StructDecl& s, std::string const& prefix = "")
    {
        sync_line(s.line);
        out_ += prefix + "struct " + s.name;
        if (s.base) out_ += " : public " + type_str(*s.base);
        out_ += " {\n";
        ++indent_;
        for (auto& f : s.fields) {
            sync_line(f.line);
            out_ += pad() + type_str(f.type) + " " + f.name + " = " + expr(*f.init) + ";\n";
        }
        --indent_;
        for (auto& md : s.methods) emit_method(s, md);
        out_ += "};\n";
    }

    void emit_method(ast::StructDecl& s, ast::MethodDecl& md)
    {
        sync_line(md.line);
        out_ += "\n";
        if (md.name == "destructor") {
            out_ += pad() + "~" + s.name + "()\n{\n";
            emit_body_of(md.name, false, nullptr, nullptr,
                         md.has_block_body, md.block_body.get(), md.expr_body.get(),
                         std::nullopt, md.line);
            out_ += pad() + "}\n";
            return;
        }
        std::string sig = "auto " + md.name + "(" + params_str(md.params, false) + ")";
        if (!md.uses_members) sig = "static " + sig;
        else if (!md.mutates) sig += " const";
        if (md.ret) sig += " -> " + ret_type_str(md.ret, md.throws);
        out_ += pad() + sig + "\n" + pad() + "{\n";
        emit_body_of(md.name, md.throws, md.pre.get(), md.post.get(),
                     md.has_block_body, md.block_body.get(), md.expr_body.get(), md.ret, md.line);
        out_ += pad() + "}\n";
    }
};

} // namespace

std::string emit_flatten(std::vector<ModuleEntry> const& units)
{
    std::string out = "// Generated by cpp2c (whole-program flatten). DO NOT EDIT.\n"
                      + prelude_includes() + "\n";

    for (auto const& e : units) {
        Emitter em;
        em.set(*e.m, *e.r, e.src_name);
        out += em.flatten_block();
        out += em.flatten_usings(e.is_root);
        out += "\n";
    }
    for (auto const& e : units) {
        if (!e.is_root) continue;
        Emitter em;
        em.set(*e.m, *e.r, e.src_name);
        out += em.main_definition();
    }
    return out;
}

std::string emit_module_unit(ModuleEntry const& e)
{
    Emitter em;
    em.set(*e.m, *e.r, e.src_name);
    return em.module_unit(e);
}

std::pair<std::string, std::string> emit_bridge(std::vector<ModuleEntry> const& units,
                                                std::string const& libname)
{
    std::string h;    // banner/include 由 bridge_header/bridge_impl 各自生成一次
    std::string cpp;

    for (auto const& e : units) {
        Emitter em;
        em.set(*e.m, *e.r, e.src_name);
        h += em.bridge_header(libname);
        cpp += em.bridge_impl(libname);
    }
    return {h, cpp};
}

} // namespace cpp2::emit
