// C++2 → C++23 发射器实现(M3 摊平/模块/桥接 + M2d 泛型/variant/match/lambda
//                          + M3b headers 后端)
#include "emit.hpp"
#include "util.hpp"
#include "stdbridge/registry.hpp"           // M9:stdbridge 单表(类型面)

#include <unordered_map>
#include <unordered_set>

namespace cpp2::emit {

namespace {

int bin_prec(std::string const& op)
{
    if (op == "||") return 1;
    if (op == "&&") return 2;
    if (op == "=")  return 2;
    if (op == "==" || op == "!=") return 3;
    if (op == "<" || op == ">" || op == "<=" || op == ">=") return 4;
    if (op == "<<" || op == ">>") return 5;
    if (op == "+" || op == "-" || op == "*" || op == "/" || op == "%") return 6;
    return 0;
}

int expr_prec(ast::Expr& e)
{
    switch (e.kind()) {
    case ast::Expr::Binary: return bin_prec(static_cast<ast::BinaryExpr&>(e).op);
    case ast::Expr::Unary:  return 7;
    default:                return 8;
    }
}

std::string escape_path(std::string p)
{
    std::string out;
    for (char c : p) {
        if (c == '\\') out += '/';
        else if (c == '"') out += "\\\"";
        else out += c;
    }
    return out;
}

std::string prelude_includes()
{
    return std::string("#include \"cpp2/support.hpp\"\n")
         + "#include \"cpp2/std.hpp\"\n"        // M9:自研 std(string/vector/map)
         + "#include <cmath>\n#include <cstdint>\n#include <filesystem>\n"
           "#include <fstream>\n#include <optional>\n#include <string>\n"
           "#include <utility>\n#include <variant>\n#include <vector>\n";
}

// "app.util" → {cpp2mod, app, util}(用于摊平模式的嵌套命名空间与 using)
std::vector<std::string> ns_parts(std::string const& module_name)
{
    std::vector<std::string> parts{"cpp2mod"};
    std::string cur;
    for (char c : module_name) {
        if (c == '.') { if (!cur.empty()) parts.push_back(cur); cur.clear(); }
        else cur += c;
    }
    if (!cur.empty()) parts.push_back(cur);
    return parts;
}

class Emitter {
public:
    Emitter() = default;

    void set(ast::Module& m, sema::Result const& sema, std::string const& src)
    {
        m_ = &m; sema_ = &sema;
        src_ = escape_path(src);
        out_.clear(); indent_ = 0; last_line_ = -1; fresh_ = 0; checks_on_ = true;
        suppress_line_ = false;
    }

    std::string take() { return std::move(out_); }

    void set_release(bool r) { release_ = r; }

    // cxx_legacy 块原文(M6):#line 映射后逐字输出(全局域)
    std::string legacy_text() const
    {
        if (!m_ || m_->legacy_blocks.empty()) return {};
        std::string s;
        for (auto& lb : m_->legacy_blocks) {
            s += "#line " + std::to_string(lb.line) + " \"" + src_ + "\"\n";
            s += lb.code;
            s += "\n";
        }
        return s;
    }

    // ═══ 模式一:摊平(命名空间块,main 除外)═══════════════════════
    std::string flatten_block()
    {
        auto parts = ns_parts(m_->name);
        out_ += "namespace " + parts[0] + " {\n";
        for (size_t i = 1; i < parts.size(); ++i)
            out_ += "namespace " + parts[i] + " {\n";
        ++indent_;
        decls(/*emit_main*/false, /*exported_visible*/false);
        --indent_;
        for (size_t i = 0; i < parts.size(); ++i) out_ += "}\n";
        return out_;
    }

    // 摊平模式的 using 提升:非 root 只提升导出名;root 提升全部(main 需要见兄弟)
    std::string flatten_usings(bool hoist_all)
    {
        std::string q;
        for (auto& p : ns_parts(m_->name)) q += (q.empty() ? "" : "::") + p;

        std::string s;
        auto hoist = [&](std::string const& n) {
            s += "using " + q + "::" + n + ";\n";
        };
        for (auto& e : m_->enums)    if (e.exported || hoist_all) hoist(e.name);
        for (auto& s2 : m_->structs) if (s2.exported || hoist_all) hoist(s2.name);
        for (auto& v : m_->variants) if (v.exported || hoist_all) hoist(v.name);
        for (auto& c : m_->concepts) if (c.exported || hoist_all) hoist(c.name);
        for (auto& g : m_->globals)  if (g.exported || hoist_all) hoist(g.name);
        for (auto& f : m_->funcs)
            if (f.name != "main" && !f.is_extern) hoist(f.name);   // extern 已在全局域(M6)
        return s;
    }

    std::string main_definition()
    {
        for (auto& f : m_->funcs)
            if (f.name == "main") { emit_definition(f); return out_; }
        return {};
    }

    // ═══ 模式二:C++20 模块单元 ════════════════════════════════════
    // root(含 main)→ 普通 TU + import 依赖;其余 → export module
    std::string module_unit(ModuleEntry const& e)
    {
        out_ = "// Generated by cpp2c from '" + src_ + "'. DO NOT EDIT.\n";
        if (!e.is_root) {
            out_ += "module;\n" + prelude_includes() + "\n" + legacy_text();
            bool any_export = false;
            for (auto& f : m_->funcs)    if (f.exported) any_export = true;
            for (auto& s : m_->structs)  if (s.exported) any_export = true;
            for (auto& en : m_->enums)   if (en.exported) any_export = true;
            for (auto& v : m_->variants) if (v.exported) any_export = true;
            for (auto& c : m_->concepts) if (c.exported) any_export = true;
            for (auto& g : m_->globals)  if (g.exported) any_export = true;
            out_ += std::string(any_export ? "export module " : "module ") + m_->name + ";\n";
        } else {
            out_ += prelude_includes() + "\n";
        }
        for (auto& imp : e.imports) out_ += "import " + imp + ";\n";
        if (!e.imports.empty()) out_ += "\n";

        // 导出实体(先原型,后定义;root TU 内同 TU 可见)
        for (auto& en : m_->enums)    if (en.exported)  emit_enum(en, e.is_root ? "" : "export ");
        for (auto& s : m_->structs)   if (s.exported)   emit_struct(s, e.is_root ? "" : "export ");
        for (auto& v : m_->variants)  if (v.exported)   emit_variant(v, e.is_root ? "" : "export ");
        for (auto& c : m_->concepts)  if (c.exported)   emit_concept(c, e.is_root ? "" : "export ");
        for (auto& g : m_->globals)   if (g.exported)   emit_global(g, e.is_root ? "" : "export ");

        bool wrote_exported_proto = false;
        for (auto& f : m_->funcs) {
            if (f.name == "main" || !f.exported) continue;
            emit_prototype(f, e.is_root ? "" : "export ");
            wrote_exported_proto = true;
        }
        if (wrote_exported_proto) out_ += "\n";

        // 内部实体 → 匿名命名空间(内部链接;DESIGN §4.7)
        bool has_internal = false;
        for (auto& en : m_->enums)    if (!en.exported) has_internal = true;
        for (auto& s : m_->structs)   if (!s.exported) has_internal = true;
        for (auto& v : m_->variants)  if (!v.exported) has_internal = true;
        for (auto& c : m_->concepts)  if (!c.exported) has_internal = true;
        for (auto& g : m_->globals)   if (!g.exported) has_internal = true;
        for (auto& f : m_->funcs)     if (!f.exported && f.name != "main") has_internal = true;
        if (has_internal) {
            out_ += "namespace {\n\n";
            ++indent_;
            for (auto& en : m_->enums)    if (!en.exported) emit_enum(en);
            for (auto& s : m_->structs)   if (!s.exported) emit_struct(s);
            for (auto& v : m_->variants)  if (!v.exported) emit_variant(v);
            for (auto& c : m_->concepts)  if (!c.exported) emit_concept(c);
            for (auto& g : m_->globals)   if (!g.exported) emit_global(g);
            for (auto& f : m_->funcs)     if (!f.exported && f.name != "main") emit_prototype(f);
            out_ += "\n";
            for (auto& f : m_->funcs)     if (!f.exported && f.name != "main") emit_definition(f);
            --indent_;
            out_ += "} // namespace\n\n";
        }

        // 导出函数定义(重新声明不带 export;匿名内部已可见)
        for (auto& f : m_->funcs) {
            if (f.name == "main" || !f.exported) continue;
            emit_definition(f);
        }
        if (e.is_root) {
            for (auto& f : m_->funcs)
                if (f.name == "main") emit_definition(f);
        }
        return out_;
    }

    // ═══ 模式三:桥接(.h 声明 / .cpp 定义)════════════════════════
    std::string bridge_header(std::string const& libname)
    {
        out_ = "// Generated by cpp2c (export-headers): bridge for Cpp1 consumers.\n"
               "// DO NOT EDIT.\n#pragma once\n";
        out_ += prelude_includes() + "\n";
        for (auto& en : m_->enums)   if (en.exported) emit_enum(en);
        for (auto& s : m_->structs)  if (s.exported) emit_struct(s);
        for (auto& v : m_->variants) if (v.exported) emit_variant(v);
        for (auto& c : m_->concepts) if (c.exported) emit_concept(c);
        for (auto& g : m_->globals)  if (g.exported) {
            sync_line(g.line);
            out_ += "extern " + type_str(g.type) + " " + g.name + ";\n";
        }
        for (auto& f : m_->funcs) {
            if (!f.exported || f.name == "main") continue;
            emit_prototype(f);
        }
        (void)libname;
        return out_;
    }

    std::string bridge_impl(std::string const& libname)
    {
        out_ = "// Generated by cpp2c (export-headers). DO NOT EDIT.\n";
        out_ += "#include \"" + libname + ".h\"\n\n";

        // 内部实体:匿名命名空间(限制:导出函数体不得引用跨模块内部名)
        bool has_internal = false;
        for (auto& en : m_->enums)   if (!en.exported) has_internal = true;
        for (auto& s : m_->structs)  if (!s.exported) has_internal = true;
        for (auto& g : m_->globals) if (!g.exported) has_internal = true;
        for (auto& f : m_->funcs)    if (!f.exported && f.name != "main") has_internal = true;
        if (has_internal) {
            out_ += "namespace {\n\n";
            ++indent_;
            for (auto& en : m_->enums)   if (!en.exported) emit_enum(en);
            for (auto& s : m_->structs)  if (!s.exported) emit_struct(s);
            for (auto& g : m_->globals) if (!g.exported) emit_global(g);
            for (auto& f : m_->funcs)    if (!f.exported && f.name != "main") emit_prototype(f);
            out_ += "\n";
            for (auto& f : m_->funcs)    if (!f.exported && f.name != "main") emit_definition(f);
            --indent_;
            out_ += "} // namespace\n\n";
        }

        for (auto& g : m_->globals) if (g.exported) emit_global(g);
        for (auto& f : m_->funcs) {
            if (!f.exported || f.name == "main") continue;
            emit_definition(f);
        }
        return out_;
    }

    // ═══ 模式四:headers 后端(每模块 .h 接口 + 实现片段)══════════
    // 不依赖 C++20 modules;方法/函数体全部线外落片段 → 改实现不触碰 .h,
    // 依赖者零重编。实现片段自带 #include 自身 .h,装箱拼接即自包含。
    std::string headers_header(std::vector<std::string> const& imports)
    {
        out_ = "// Generated by cpp2c (headers backend). DO NOT EDIT.\n#pragma once\n";
        out_ += prelude_includes() + "\n";
        for (auto& imp : imports)
            out_ += "#include \"" + cpp2::util::safe_name(imp) + ".h\"\n";
        if (!imports.empty()) out_ += "\n";

        // 导出类型(结构体只带方法声明,实现落实现片段)
        for (auto& en : m_->enums)    if (en.exported)  emit_enum(en);
        for (auto& s : m_->structs)   if (s.exported)   emit_struct_header(s);
        for (auto& v : m_->variants)  if (v.exported)   emit_variant(v);
        for (auto& c : m_->concepts)  if (c.exported)   emit_concept(c);
        for (auto& g : m_->globals)   if (g.exported)   emit_global_header(g);

        bool any = false;
        for (auto& f : m_->funcs) {
            if (!f.exported || f.name == "main") continue;
            emit_prototype(f);                        // 原型(带默认实参)
            if (!f.type_params.empty())
                emit_definition(f);                   // 模板:整定义必须进头
            any = true;
        }
        if (any) out_ += "\n";
        return out_;
    }

    std::string headers_impl(bool is_root)
    {
        std::string self = cpp2::util::safe_name(m_->name) + ".h";
        out_ = std::string("// Generated by cpp2c (headers backend). DO NOT EDIT.\n")
             + "#include \"" + self + "\"\n\n"
             + legacy_text();                 // cxx_legacy:片段顶部全局域(M6)

        // 内部实体:匿名命名空间(内部链接;DESIGN §4.7)
        bool has_internal = false;
        for (auto& en : m_->enums)    if (!en.exported) has_internal = true;
        for (auto& s : m_->structs)   if (!s.exported) has_internal = true;
        for (auto& v : m_->variants)  if (!v.exported) has_internal = true;
        for (auto& c : m_->concepts)  if (!c.exported) has_internal = true;
        for (auto& g : m_->globals)   if (!g.exported) has_internal = true;
        for (auto& f : m_->funcs)     if (!f.exported && f.name != "main") has_internal = true;
        if (has_internal) {
            out_ += "namespace {\n\n";
            ++indent_;
            for (auto& en : m_->enums)    if (!en.exported) emit_enum(en);
            for (auto& s : m_->structs)   if (!s.exported)  emit_struct(s);
            for (auto& v : m_->variants)  if (!v.exported)  emit_variant(v);
            for (auto& c : m_->concepts)  if (!c.exported)  emit_concept(c);
            for (auto& g : m_->globals)   if (!g.exported)  emit_global(g);
            for (auto& f : m_->funcs)     if (!f.exported && f.name != "main") emit_prototype(f);
            out_ += "\n";
            for (auto& f : m_->funcs)     if (!f.exported && f.name != "main") emit_definition(f);
            --indent_;
            out_ += "} // namespace\n\n";
        }

        // 导出结构体方法:线外定义(头里只有声明)
        for (auto& s : m_->structs) if (s.exported)
            for (auto& md : s.methods) emit_method_def(s, md);

        // 导出函数定义(模板已在头文件,跳过)
        for (auto& f : m_->funcs) {
            if (!f.exported || f.name == "main" || !f.type_params.empty()) continue;
            emit_definition(f);
        }

        if (is_root)
            for (auto& f : m_->funcs)
                if (f.name == "main") emit_definition(f);
        return out_;
    }

private:
    ast::Module* m_ = nullptr;
    sema::Result const* sema_ = nullptr;
    std::string src_;
    std::string out_;
    int indent_ = 0;
    int last_line_ = -1;
    int fresh_ = 0;
    bool checks_on_ = true;
    bool release_ = false;                // §6.7 Release 档位:溢出检查关、post/old 关
    bool suppress_line_ = false;      // 表达式内嵌语句序列(lambda/match 体)禁用 #line
    // post 契约发射状态:old(...) → 入口缓存变量;result → __c2_result
    // (throws 函数包 expected 需解引用;普通函数直接引用)
    std::unordered_map<ast::Expr*, std::string> const* old_names_ = nullptr;
    bool in_post_ = false;
    bool result_wrapped_ = false;

    sema::Type type_of(ast::Expr& e) const { return sema_->type_of(e); }

    // ── 声明序列(命名空间/匿名块内部通用;main 除外)──────────────
    // 顺序:enum → struct → variant → concept(替身引用结构体;概念被函数用)
    void decls(bool emit_main, bool)
    {
        for (auto& e : m_->enums)    emit_enum(e);
        for (auto& s : m_->structs)  emit_struct(s);
        for (auto& v : m_->variants) emit_variant(v);
        for (auto& c : m_->concepts) emit_concept(c);
        for (auto& g : m_->globals)  emit_global(g);
        for (auto& f : m_->funcs)    if (f.name != "main") emit_prototype(f);
        out_ += "\n";
        for (auto& f : m_->funcs) {
            if (f.name == "main" && !emit_main) continue;
            emit_definition(f);
        }
    }

    // ── 类型与名字映射(IMPL §4.7 stdbridge)───────────────────────
    // 落点统一收进 stdbridge/registry.hpp 单表:string/vector/list/map →
    // 自研 std(rt/cpp2/std),其余条目见该表;未注册名原样透传
    // (std::... 直写 = 互操作 escape hatch,DESIGN §9.1)。
    static std::string map_type_name(std::string const& n)
    {
        if (auto* r = stdbridge::map_type(n)) return *r;
        return n;
    }

    std::string type_str(ast::TypeUse const& t)
    {
        if (t.parts.empty()) return "void";
        std::string s = map_type_name(t.parts[0]);
        for (size_t i = 1; i < t.parts.size(); ++i) s += "::" + t.parts[i];
        if (!t.args.empty()) {
            s += "<";
            for (size_t i = 0; i < t.args.size(); ++i) {
                if (i) s += ", ";
                s += type_str(t.args[i]);
            }
            s += ">";
        }
        if (t.is_optional) s = "std::optional<" + s + ">";   // T?(M2d,DESIGN §6.4)
        if (t.is_const) s += " const";
        if (t.is_pointer) s += "*";                          // T*(M6,L5)
        return s;
    }

    std::string name_expr_str(ast::NameExpr& n)
    {
        if (n.parts.size() == 2 && n.parts[0] == "std") {
            if (n.parts[1] == "print" || n.parts[1] == "println")
                return "cpp2::stdx::" + n.parts[1];
            return "std::" + n.parts[1];
        }
        if (n.parts.size() == 1
            && (n.parts[0] == "make_unique" || n.parts[0] == "make_shared"))
            return "cpp2::" + n.parts[0];
        std::string s = n.parts[0];
        for (size_t i = 1; i < n.parts.size(); ++i) s += "::" + n.parts[i];
        return s;
    }

    std::string check_loc(int line) const
    {
        return ", \"" + src_ + "\", " + std::to_string(line);
    }

    static std::string cpp_type_of(sema::Type const& t)
    {
        switch (t.kind) {
        case sema::Type::Int:  return "int";
        case sema::Type::I8:   return "std::int8_t";
        case sema::Type::I16:  return "std::int16_t";
        case sema::Type::I32:  return "std::int32_t";
        case sema::Type::I64:  return "std::int64_t";
        case sema::Type::U8:   return "std::uint8_t";
        case sema::Type::U16:  return "std::uint16_t";
        case sema::Type::U32:  return "std::uint32_t";
        case sema::Type::U64:  return "std::uint64_t";
        default:               return "int";
        }
    }

    std::string checked_call(std::string const& fn, ast::Expr& l, ast::Expr& r,
                             sema::Type const& res, int line)
    {
        std::string t = cpp_type_of(res);
        return "cpp2::" + fn + "(static_cast<" + t + ">(" + expr(l)
             + "), static_cast<" + t + ">(" + expr(r) + ")" + check_loc(line) + ")";
    }

    // ── builtin 原语 → headers(rt cpp2)实现表 ─────────────────────
    // 单一登记点 = 语言面↔rt 的契约。native 侧对应表在 native.cpp
    // (机器码/thunk);新增原语需两表同步 + rt 实现。
    static std::string const* builtin_rt_name(std::string const& n)
    {
        static std::unordered_map<std::string, std::string> const map{
            {"write_stdout", "cpp2_write"},        // (const char*, int)
            {"write_char",   "cpp2_write_char"},   // (char)
            {"sys_exit",     "cpp2_exit"},         // (int)
        };
        auto it = map.find(n);
        return it != map.end() ? &it->second : nullptr;
    }

    // ── 表达式 ─────────────────────────────────────────────────────
    std::string expr(ast::Expr& e)
    {
        switch (e.kind()) {
        case ast::Expr::Literal:
            return static_cast<ast::LiteralExpr&>(e).text;
        case ast::Expr::Name: {
            auto& n = static_cast<ast::NameExpr&>(e);
            if (in_post_ && n.parts.size() == 1 && n.parts[0] == "result")
                return result_wrapped_ ? "(*__c2_result)" : "__c2_result";
            if (n.parts.size() == 1 && n.parts[0] == "none"
                && type_of(e).kind == sema::Type::NoneVal)
                return "std::nullopt";        // 空 optional(DESIGN §6.4)
            return name_expr_str(n);
        }
        case ast::Expr::Paren:
            return "(" + expr(*static_cast<ast::ParenExpr&>(e).inner) + ")";
        case ast::Expr::Call: {
            auto& c = static_cast<ast::CallExpr&>(e);
            // post 契约中的 old(...) → 入口缓存变量(sema 保证仅 post 出现)
            if (old_names_) {
                auto it = old_names_->find(&c);
                if (it != old_names_->end()) return it->second;
            }
            // err("msg"[, category]) → cpp2::err(...)(sema 已标 ErrVal)
            if (c.callee->kind() == ast::Expr::Name && (c.args.size() == 1 || c.args.size() == 2)
                && type_of(c).kind == sema::Type::ErrVal) {
                auto& name = static_cast<ast::NameExpr&>(*c.callee);
                if (name.parts.size() == 1 && name.parts[0] == "err") {
                    if (c.args.size() == 2)
                        return "cpp2::err(" + expr(*c.args[1]) + ", " + expr(*c.args[0])
                             + check_loc(c.line) + ")";
                    return "cpp2::err(" + expr(*c.args[0]) + check_loc(c.line) + ")";
                }
            }
            // UFCS:x.f(args) → f(x, args)(DESIGN §4.7;sema 已定向)
            if (c.callee->kind() == ast::Expr::Member) {
                std::string target = sema_->ufcs_of(c);
                if (!target.empty()) {
                    auto& mem = static_cast<ast::MemberExpr&>(*c.callee);
                    std::string s = target + "(" + expr(*mem.base);
                    for (auto& a : c.args) s += ", " + expr(*a);
                    return s + ")";
                }
            }
            // builtin 原语调用 → rt 实现(见 builtin_rt_name 表)
            if (c.callee->kind() == ast::Expr::Name) {
                auto& nm0 = static_cast<ast::NameExpr&>(*c.callee);
                if (!nm0.qualified())
                    if (auto* rt = builtin_rt_name(nm0.parts[0])) {
                        std::string s = *rt + "(";
                        for (size_t i = 0; i < c.args.size(); ++i) {
                            if (i) s += ", ";
                            s += expr(*c.args[i]);
                        }
                        return s + ")";
                    }
            }
            std::string s = expr(*c.callee) + "(";
            for (size_t i = 0; i < c.args.size(); ++i) {
                if (i) s += ", ";
                s += expr(*c.args[i]);
            }
            return s + ")";
        }
        case ast::Expr::Binary: {
            auto& b = static_cast<ast::BinaryExpr&>(e);
            // §6.7:Release 档位关闭有符号算术溢出检查(越界/空/契约保留)
            if (checks_on_ && !release_
                && (b.op == "+" || b.op == "-" || b.op == "*"
                 || b.op == "/" || b.op == "%")) {
                sema::Type l = type_of(*b.lhs), r = type_of(*b.rhs);
                if (l.is_signed() && r.is_signed()) {
                    std::string fn = b.op == "+" ? "checked_add"
                                  : b.op == "-" ? "checked_sub"
                                  : b.op == "*" ? "checked_mul"
                                  : b.op == "/" ? "checked_div"
                                                : "checked_mod";
                    return checked_call(fn, *b.lhs, *b.rhs, type_of(b), b.line);
                }
            }
            int p = bin_prec(b.op);
            std::string l = expr(*b.lhs);
            std::string r = expr(*b.rhs);
            if (expr_prec(*b.lhs) < p) l = "(" + l + ")";
            if (expr_prec(*b.rhs) <= p && b.rhs->kind() == ast::Expr::Binary) r = "(" + r + ")";
            return l + " " + b.op + " " + r;
        }
        case ast::Expr::Unary: {
            auto& u = static_cast<ast::UnaryExpr&>(e);
            if (u.op == "move")
                return "std::move(" + expr(*u.operand) + ")";
            std::string s = expr(*u.operand);
            if (expr_prec(*u.operand) < 7) s = "(" + s + ")";
            return u.op + s;
        }
        case ast::Expr::Assign: {
            auto& a = static_cast<ast::AssignExpr&>(e);
            return expr(*a.target) + " " + a.op + " " + expr(*a.value);
        }
        case ast::Expr::Index: {
            auto& x = static_cast<ast::IndexExpr&>(e);
            sema::Type b = type_of(*x.base);
            if (checks_on_ && b.is_indexable()) {
                return "cpp2::index(" + expr(*x.base) + ", " + expr(*x.index)
                     + check_loc(x.line) + ")";
            }
            std::string s = expr(*x.base);
            if (expr_prec(*x.base) < 8) s = "(" + s + ")";
            return s + "[" + expr(*x.index) + "]";
        }
        case ast::Expr::Member: {
            auto& x = static_cast<ast::MemberExpr&>(e);
            sema::Type b = type_of(*x.base);
            std::string s = expr(*x.base);
            if (expr_prec(*x.base) < 8) s = "(" + s + ")";
            if (b.is_smart()) {
                // '.' 自动解引用经空检查(DESIGN §6.4):deref(p)->member
                if (checks_on_)
                    return "cpp2::deref(" + s + check_loc(x.line) + ")->" + x.name;
                return s + "->" + x.name;
            }
            return s + "." + x.name;
        }
        case ast::Expr::StructLit: {
            auto& l = static_cast<ast::StructLitExpr&>(e);
            std::string name = map_type_name(l.type_parts[0]);
            for (size_t i = 1; i < l.type_parts.size(); ++i) name += "::" + l.type_parts[i];

            std::vector<std::pair<std::string, ast::Expr*>> ordered;
            if (l.type_parts.size() == 1) {
                if (auto* sd = m_->find_struct(l.type_parts[0])) {
                    for (auto* f : fields_of(*sd)) {
                        for (auto& [fn, fv] : l.fields)
                            if (fn == f->name) ordered.push_back({fn, fv.get()});
                    }
                }
            }
            if (ordered.empty())
                for (auto& [fn, fv] : l.fields) ordered.push_back({fn, fv.get()});

            std::string s = name + "{";
            for (size_t i = 0; i < ordered.size(); ++i) {
                if (i) s += ", ";
                s += "." + ordered[i].first + " = " + expr(*ordered[i].second);
            }
            return s + "}";
        }
        case ast::Expr::AsCast: {
            auto& x = static_cast<ast::AsCastExpr&>(e);
            sema::Type src = type_of(*x.operand);
            sema::Type dst = type_from_target(x.target);
            std::string inner = expr(*x.operand);
            if (expr_prec(*x.operand) < 8) inner = "(" + inner + ")";
            std::string t = type_str(x.target);
            // 宽化(值域变大)发 static_cast:narrow_cast 的边界回卷对宽化必错
            // (int→i64 边界回卷 -1、int→double 回卷 INT_MIN,实测踩坑 M6)
            bool widening = src.is_widening_to(dst);
            if (checks_on_ && src.is_arith() && dst.is_arith() && !widening)
                return "cpp2::narrow_cast<" + t + ">(" + inner + check_loc(x.line) + ")";
            return "static_cast<" + t + ">(" + inner + ")";
        }
        case ast::Expr::ListLit: {
            auto& l = static_cast<ast::ListLitExpr&>(e);
            if (l.elements.empty()) return "{}";   // 声明侧已定型:list<int> v = {}
            // M9:自研 vector CTAD(list/vector 都落 cpp2::vector,rgstr 表驱动)
            std::string s = map_type_name("vector") + "{";
            for (size_t i = 0; i < l.elements.size(); ++i) {
                if (i) s += ", ";
                s += expr(*l.elements[i]);
            }
            return s + "}";
        }
        case ast::Expr::Must: {
            // f()! → cpp2::must(f(), "file", line);失败即 bug → trap(DESIGN §8.2)
            auto& x = static_cast<ast::MustExpr&>(e);
            return "(cpp2::must(" + expr(*x.operand) + check_loc(x.line) + "))";
        }
        case ast::Expr::OrDefault: {
            // f() or "d" → (f()).value_or("d")(DESIGN §8.3)
            auto& x = static_cast<ast::OrDefaultExpr&>(e);
            return "(" + expr(*x.lhs) + ").value_or((" + expr(*x.rhs) + "))";
        }
        case ast::Expr::Try:
            // '?' 的机械展开需要语句级拆分,由 emit_stmt 处理;
            // 走到这里说明 sema 漏检——发射防御性标记,生成码编译期暴露
            return "/*internal:'?' outside statement position*/ ("
                 + expr(*static_cast<ast::TryExpr&>(e).operand) + ")";
        case ast::Expr::Match:
            // match 产值:提升为 IIFE 语句,返回值变量(sema 限定语句级位置;
            // 语句行随后拼接,提升行先落 out_,顺序正确)
            return emit_match_value(static_cast<ast::MatchExpr&>(e));
        case ast::Expr::Lambda:
            return emit_lambda(static_cast<ast::LambdaExpr&>(e));
        }
        return "/*?*/";
    }

    sema::Type type_from_target(ast::TypeUse const& tu)
    {
        std::string n = tu.parts.empty() ? "" : tu.parts.back();
        sema::Type t;
        if (n == "int" || n == "i8" || n == "i16" || n == "i32" || n == "i64"
         || n == "int32_t" || n == "int64_t") t.kind = sema::Type::Int;
        else if (n == "u8" || n == "u16" || n == "u32" || n == "u64"
              || n == "uint32_t" || n == "uint64_t") t.kind = sema::Type::U32;
        else if (n == "double" || n == "float") t.kind = sema::Type::Double;
        else if (n == "bool") t.kind = sema::Type::Bool;
        else if (n == "char") t.kind = sema::Type::Char;
        return t;
    }

    std::vector<ast::FieldDecl*> fields_of(ast::StructDecl& s)
    {
        std::vector<ast::FieldDecl*> out;
        if (s.base && s.base->parts.size() == 1)
            if (auto* b = m_->find_struct(s.base->parts[0])) {
                auto base_fields = fields_of(*b);
                out.insert(out.end(), base_fields.begin(), base_fields.end());
            }
        for (auto& f : s.fields) out.push_back(&f);
        return out;
    }

    // ── 语句 ───────────────────────────────────────────────────────
    std::string pad() const { return std::string(indent_ * 4, ' '); }

    void sync_line(int line)
    {
        if (suppress_line_) return;
        if (line > 0 && line != last_line_) {
            out_ += "#line " + std::to_string(line) + " \"" + src_ + "\"\n";
            last_line_ = line;
        }
    }

    // 表达式内嵌语句序列(lambda 体 / match 表达式体):独立缓冲渲染。
    // #line 指令不能出现在表达式中间,故整体禁用(位置由外围语句的 sync_line 承担)。
    template <class F>
    std::string render_nested(F&& fn)
    {
        std::string save = std::move(out_);
        int save_indent = indent_;
        int save_line = last_line_;
        bool save_sup = suppress_line_;
        out_.clear();
        last_line_ = -1;
        suppress_line_ = true;
        fn();
        std::string body = std::move(out_);
        out_ = std::move(save);
        indent_ = save_indent;
        last_line_ = save_line;
        suppress_line_ = save_sup;
        return body;
    }

    void emit_body(ast::Stmt& s)
    {
        if (s.kind() == ast::Stmt::Block) {
            for (auto& st : static_cast<ast::BlockStmt&>(s).stmts) emit_stmt(*st);
        } else {
            emit_stmt(s);
        }
    }

    void emit_stmt(ast::Stmt& s)
    {
        bool prev_checks = checks_on_;
        checks_on_ = checks_on_ && !s.no_check;

        switch (s.kind()) {
        case ast::Stmt::ExprStmt: {
            auto& x = static_cast<ast::ExprStmt&>(s);
            if (x.expr->kind() == ast::Expr::Try) {
                // 裸 f()?;:检查 + 传播,丢弃值(expected<void> 风格的调用点)
                sync_line(s.line);
                emit_try_core(static_cast<ast::TryExpr&>(*x.expr));
                break;
            }
            if (x.expr->kind() == ast::Expr::Assign) {
                auto& a = static_cast<ast::AssignExpr&>(*x.expr);
                sync_line(s.line);
                if (a.value->kind() == ast::Expr::Try && a.op == "=") {
                    // x = f()?;:右值机械展开(临时量作用域隔离)
                    out_ += pad() + "{\n";
                    ++indent_;
                    std::string tmp = emit_try_core(static_cast<ast::TryExpr&>(*a.value));
                    out_ += pad() + expr(*a.target) + " = *std::move(" + tmp + ");\n";
                    --indent_;
                    out_ += pad() + "}\n";
                    break;
                }
                if (a.op != "=" && checks_on_ && !release_) {
                    sema::Type t = type_of(*a.target);
                    if (t.is_signed()) {
                        std::string fn = a.op == "+=" ? "checked_add"
                                       : a.op == "-=" ? "checked_sub"
                                       : a.op == "*=" ? "checked_mul"
                                       : a.op == "/=" ? "checked_div"
                                                      : "checked_mod";
                        std::string target = expr(*a.target);
                        out_ += pad() + target + " = "
                              + checked_call(fn, *a.target, *a.value, t, a.line) + ";\n";
                        break;
                    }
                }
                out_ += pad() + expr(*x.expr) + ";\n";
            } else {
                sync_line(s.line);
                out_ += pad() + "(void)(" + expr(*x.expr) + ");\n";
            }
            break;
        }
        case ast::Stmt::Return: {
            auto& r = static_cast<ast::ReturnStmt&>(s);
            sync_line(s.line);
            if (r.value && r.value->kind() == ast::Expr::Try) {
                // return f()?;:失败提前 return unexpected,成功解包
                std::string tmp = emit_try_core(static_cast<ast::TryExpr&>(*r.value));
                out_ += pad() + "return *std::move(" + tmp + ");\n";
                break;
            }
            out_ += pad() + (r.value ? "return " + expr(*r.value) + ";\n" : "return;\n");
            break;
        }
        case ast::Stmt::Var: {
            auto& v = static_cast<ast::VarStmt&>(s);
            sync_line(v.line);
            std::string type = v.has_type ? type_str(v.type)
                              : (v.is_const ? "auto const" : "auto");
            if (v.init && v.init->kind() == ast::Expr::Try) {
                // x := f()?; 机械展开(IMPL §4.3):求值 → 失败传播 → 解包绑定
                std::string tmp = emit_try_core(static_cast<ast::TryExpr&>(*v.init));
                out_ += pad() + type + " " + v.name + " = *std::move(" + tmp + ");\n";
                break;
            }
            out_ += pad() + type + " " + v.name + " = " + expr(*v.init) + ";\n";
            break;
        }
        case ast::Stmt::If: {
            auto& i = static_cast<ast::IfStmt&>(s);
            sync_line(s.line);
            if (i.is_let()) {
                emit_if_let(i);
                break;
            }
            out_ += pad() + "if (" + expr(*i.cond) + ") {\n";
            ++indent_;
            emit_body(*i.then_block);
            --indent_;
            if (i.else_block) {
                out_ += pad() + "} else ";
                if (i.else_block->kind() == ast::Stmt::If)
                    emit_if_inline(static_cast<ast::IfStmt&>(*i.else_block));
                else {
                    out_ += "{\n";
                    ++indent_;
                    emit_body(*i.else_block);
                    --indent_;
                    out_ += pad() + "}\n";
                }
            } else {
                out_ += pad() + "}\n";
            }
            break;
        }
        case ast::Stmt::While: {
            auto& w = static_cast<ast::WhileStmt&>(s);
            sync_line(s.line);
            out_ += pad() + "while (" + expr(*w.cond) + ") {\n";
            ++indent_;
            emit_body(*w.body);
            --indent_;
            out_ += pad() + "}\n";
            break;
        }
        case ast::Stmt::For:
            emit_for(static_cast<ast::ForStmt&>(s));
            break;
        case ast::Stmt::Break:    sync_line(s.line); out_ += pad() + "break;\n"; break;
        case ast::Stmt::Continue: sync_line(s.line); out_ += pad() + "continue;\n"; break;
        case ast::Stmt::Block: {
            auto& b = static_cast<ast::BlockStmt&>(s);
            sync_line(s.line);
            out_ += pad() + "{\n";
            ++indent_;
            for (auto& st : b.stmts) emit_stmt(*st);
            --indent_;
            out_ += pad() + "}\n";
            break;
        }
        case ast::Stmt::Match:
            emit_match(static_cast<ast::MatchStmt&>(s));
            break;
        }

        checks_on_ = prev_checks;
    }

    // '?' 核心展开:求值到临时量,失败提前 return unexpected;返回临时量名。
    // 解包/绑定/丢弃由调用侧追加(变量初始化 / return / 赋值 / 裸语句)。
    std::string emit_try_core(ast::TryExpr& t)
    {
        std::string tmp = "__c2_try_" + std::to_string(fresh_++);
        out_ += pad() + "auto " + tmp + " = (" + expr(*t.operand) + ");\n";
        out_ += pad() + "if (!" + tmp + ") { return cpp2::unexpected(std::move("
              + tmp + ").error()); }\n";
        return tmp;
    }

    // if x := f() { } else e := it { }:has_value 分支 + 错误绑定(DESIGN §8.3)
    void emit_if_let(ast::IfStmt& i)
    {
        std::string tmp = "__c2_if_" + std::to_string(fresh_++);
        out_ += pad() + "{\n";
        ++indent_;
        out_ += pad() + "auto&& " + tmp + " = (" + expr(*i.let_init) + ");\n";
        out_ += pad() + "if (" + tmp + ".has_value()) {\n";
        ++indent_;
        if (i.let_name != "_")
            out_ += pad() + "auto&& " + i.let_name + " = *" + tmp + ";\n";
        emit_body(*i.then_block);
        --indent_;
        if (i.else_block) {
            out_ += pad() + "} else {\n";
            ++indent_;
            if (!i.else_binding.empty())
                out_ += pad() + "auto&& " + i.else_binding + " = " + tmp + ".error();\n";
            emit_body(*i.else_block);
            --indent_;
        }
        out_ += pad() + "}\n";
        --indent_;
        out_ += pad() + "}\n";
    }

    // ── 模式匹配(M2d,DESIGN §4.5/§5.4/§5.5)─────────────────────────
    // scrutinee 类型分类:决定条件与访问的降低形态
    struct MatchInfo {
        enum class Kind { Expected, Optional, Enum, Variant, Struct, Bad } kind = Kind::Bad;
        std::string enum_name;
        ast::VariantDecl* vd = nullptr;
        ast::StructDecl* sd = nullptr;
    };

    MatchInfo match_info_of(ast::Expr& scrut)
    {
        sema::Type t = type_of(scrut);
        MatchInfo mi;
        if (t.is_expected)                          mi.kind = MatchInfo::Kind::Expected;
        else if (t.is_optional)                     mi.kind = MatchInfo::Kind::Optional;
        else if (t.kind == sema::Type::Variant) {
            mi.kind = MatchInfo::Kind::Variant;
            mi.vd = m_->find_variant(t.name);
        } else if (t.kind == sema::Type::NamedStruct) {
            mi.kind = MatchInfo::Kind::Struct;
            mi.sd = m_->find_struct(t.name);
        } else if (t.kind == sema::Type::NamedEnum) {
            mi.kind = MatchInfo::Kind::Enum;
            mi.enum_name = t.name;
        }
        return mi;
    }

    // 模式类型在 variant 中的替身(sema 已按规范化键校验存在)
    std::string variant_alt_str(ast::VariantDecl& vd, ast::TypeUse const& pattern)
    {
        std::string want = type_str(pattern);
        for (auto& alt : vd.alternatives)
            if (type_str(alt) == want) return want;
        return want;
    }

    // 臂链:线性 else-if;守卫臂在其 else 分支递归续链(守卫失败 → 落入后续臂)
    void emit_arm_chain(std::vector<ast::MatchArm>& arms, size_t from, MatchInfo const& mi,
                        std::string const& tmp, bool value_form, std::string const& ret_cpp)
    {
        for (size_t k = from; k < arms.size(); ++k) {
            auto& arm = arms[k];
            bool last = k + 1 == arms.size();

            if (arm.pat == ast::MatchArm::Pat::Wildcard) {
                out_ += pad() + "} else {\n";       // '_' 只能是最后一臂(sema 保证)
                ++indent_;
                emit_arm_body(arm, value_form, ret_cpp);
                --indent_;
                out_ += pad() + "}\n";
                return;
            }

            std::string cond;
            switch (arm.pat) {
            case ast::MatchArm::Pat::Ok:
            case ast::MatchArm::Pat::Some:
                cond = tmp + ".has_value()";
                break;
            case ast::MatchArm::Pat::Err:
            case ast::MatchArm::Pat::None:
                cond = "!" + tmp + ".has_value()";
                break;
            case ast::MatchArm::Pat::EnumMember:
                cond = tmp + " == " + mi.enum_name + "::" + arm.enum_member;
                break;
            case ast::MatchArm::Pat::TypePat:
                if (mi.kind == MatchInfo::Kind::Variant && mi.vd)
                    cond = "std::holds_alternative<" + variant_alt_str(*mi.vd, arm.type_pattern)
                          + ">(" + tmp + ")";
                else
                    cond = "true";                  // struct 自身模式:恒真
                break;
            case ast::MatchArm::Pat::Wildcard:
                break;
            }

            out_ += pad() + (k == from ? "if (" : "} else if (") + cond + ") {\n";
            ++indent_;

            auto emit_binding = [&](std::string const& name, std::string const& access) {
                if (name.empty() || name == "_") return;
                std::string line = pad();
                line += "auto&& ";
                line += name;
                line += " = ";
                line += access;
                line += ";\n";
                out_ += line;
            };
            if (arm.pat == ast::MatchArm::Pat::Ok || arm.pat == ast::MatchArm::Pat::Some)
                emit_binding(arm.binding, "*" + tmp);
            else if (arm.pat == ast::MatchArm::Pat::Err)
                emit_binding(arm.binding, tmp + ".error()");
            else if (arm.pat == ast::MatchArm::Pat::TypePat) {
                std::string base_access;
                if (mi.kind == MatchInfo::Kind::Variant && mi.vd)
                    base_access = "std::get<" + variant_alt_str(*mi.vd, arm.type_pattern)
                                + ">(" + tmp + ")";
                else
                    base_access = tmp;              // struct 自身模式
                if (!arm.sub.empty()) {
                    // sema 注记形态:".field=binding"(位置/命名字段统一;含替身结构体解析)
                    for (size_t i = 0; i < arm.sub.size(); ++i) {
                        std::string const& sp = arm.sub[i];
                        if (sp == "_") continue;
                        size_t eq = sp.find('=');
                        if (sp.size() > 1 && sp[0] == '.' && eq != std::string::npos)
                            emit_binding(sp.substr(eq + 1),
                                         base_access + "." + sp.substr(1, eq - 1));
                    }
                } else {
                    emit_binding(arm.binding, base_access);
                }
            }

            if (arm.guard) {
                // 守卫臂:两条失败路径都要续链——守卫失败(else)与模式不匹配
                // (外层 else);余链在每个分支各发一份(g 守卫臂 → 2^g 膨胀,v0.1 接受)
                out_ += pad() + "if (" + expr(*arm.guard) + ") {\n";
                ++indent_;
                emit_arm_body(arm, value_form, ret_cpp);
                --indent_;
                out_ += pad() + "} else {\n";
                ++indent_;
                emit_arm_chain(arms, k + 1, mi, tmp, value_form, ret_cpp);
                --indent_;
                out_ += pad() + "}\n";
                --indent_;
                out_ += pad() + "} else {\n";
                ++indent_;
                emit_arm_chain(arms, k + 1, mi, tmp, value_form, ret_cpp);
                --indent_;
                out_ += pad() + "}\n";
                return;
            }
            emit_arm_body(arm, value_form, ret_cpp);
            --indent_;
            if (last) {
                // 穷尽性由 sema 保证;值形式的 IIFE 补不可达 trap,
                // 消除"并非所有路径都返回"警告并留运行时防御网
                if (value_form) {
                    out_ += pad() + "} else {\n";
                    ++indent_;
                    out_ += pad() + "cpp2::trap(\"unreachable match arm\""
                          + check_loc(arm.line) + ");\n";
                    --indent_;
                    out_ += pad() + "}\n";
                } else {
                    out_ += pad() + "}\n";
                }
            }
        }
    }

    // 臂体:语句形式原样;值形式 return 表达式(块体取尾表达式为返回值)
    void emit_arm_body(ast::MatchArm& arm, bool value_form, std::string const& ret_cpp)
    {
        if (!value_form) {
            emit_body(*arm.body);
            return;
        }
        auto& b = *arm.body;
        if (b.kind() == ast::Stmt::ExprStmt) {
            out_ += pad() + "return ("
                  + expr(*static_cast<ast::ExprStmt&>(b).expr) + ");\n";
            return;
        }
        if (b.kind() == ast::Stmt::Block) {
            auto& blk = static_cast<ast::BlockStmt&>(b);
            bool returns_value = !ret_cpp.empty() && ret_cpp != "void";
            for (size_t i = 0; i < blk.stmts.size(); ++i) {
                bool tail = returns_value && i + 1 == blk.stmts.size()
                            && blk.stmts[i]->kind() == ast::Stmt::ExprStmt;
                if (tail)
                    out_ += pad() + "return ("
                          + expr(*static_cast<ast::ExprStmt&>(*blk.stmts[i]).expr) + ");\n";
                else
                    emit_stmt(*blk.stmts[i]);
            }
            return;
        }
        emit_stmt(b);
    }

    // match v { ... } 语句形式:块内臂链(scrutinee 求值一次)
    void emit_match(ast::MatchStmt& x)
    {
        std::string tmp = "__c2_m_" + std::to_string(fresh_++);
        MatchInfo mi = match_info_of(*x.scrutinee);
        sync_line(x.line);
        out_ += pad() + "{\n";
        ++indent_;
        out_ += pad() + "auto&& " + tmp + " = (" + expr(*x.scrutinee) + ");\n";
        emit_arm_chain(x.arms, 0, mi, tmp, /*value_form*/false, "");
        --indent_;
        out_ += pad() + "}\n";
    }

    // match v { ... } 值形式:IIFE 产值为提升变量(语句位置消费)
    std::string emit_match_value(ast::MatchExpr& x)
    {
        std::string var = "__c2_mv_" + std::to_string(fresh_++);
        MatchInfo mi = match_info_of(*x.scrutinee);
        std::string ret_cpp = sema_type_cpp(type_of(x));
        sync_line(x.line);
        out_ += pad() + "auto " + var + " = [&]()"
              + (ret_cpp.empty() ? "" : " -> " + ret_cpp) + " {\n";
        ++indent_;
        std::string tmp = "__c2_m_" + std::to_string(fresh_++);
        out_ += pad() + "auto&& " + tmp + " = (" + expr(*x.scrutinee) + ");\n";
        emit_arm_chain(x.arms, 0, mi, tmp, /*value_form*/true, ret_cpp);
        --indent_;
        out_ += pad() + "}();\n";
        return var;
    }

    // sema 类型 → C++ 类型串(值形式 match 的返回类型标注;未知 → 省略由推导)
    std::string sema_type_cpp(sema::Type const& t)
    {
        if (t.is_optional) return "std::optional<" + sema_type_cpp(t.val()) + ">";
        switch (t.kind) {
        case sema::Type::Bool: return "bool";
        case sema::Type::Char: return "char";
        case sema::Type::Float: return "float";
        case sema::Type::Double: return "double";
        case sema::Type::String: return map_type_name("string");   // cpp2::string(M9)
        case sema::Type::StringView: return "std::string_view";
        case sema::Type::NamedStruct:
        case sema::Type::NamedEnum:
        case sema::Type::Variant:
        case sema::Type::Generic:
            return t.name;
        case sema::Type::Container:
            return map_type_name(t.name) + "<" + sema_type_cpp(t.elem()) + ">";
        case sema::Type::Map:                                       // M9:bare map
            return map_type_name(t.name) + "<" + sema_type_cpp(*t.key)
                 + ", " + sema_type_cpp(t.elem()) + ">";
        default:
            return cpp_type_of(t);
        }
    }

    // 匿名函数(DESIGN §4.6):[&](params) -> ret { body }。
    // 块体经缓冲交换用语句发射器生成;体在表达式中间多行合法。
    std::string emit_lambda(ast::LambdaExpr& l)
    {
        std::string caps = "[&]";
        if (!l.captures.empty()) {
            caps = "[";
            for (size_t i = 0; i < l.captures.size(); ++i) {
                if (i) caps += ",";
                caps += l.captures[i];
            }
            caps += "]";
        }
        std::string header = caps + "(" + params_str(l.params, /*with_defaults*/true) + ")";
        if (l.ret) header += " -> " + type_str(*l.ret);

        std::string buf;
        std::swap(out_, buf);
        ++indent_;
        if (l.has_block_body && l.block_body) {
            auto& blk = static_cast<ast::BlockStmt&>(*l.block_body);
            bool returns_value = l.ret && type_str(*l.ret) != "void";
            for (size_t i = 0; i < blk.stmts.size(); ++i) {
                bool tail = returns_value && i + 1 == blk.stmts.size()
                            && blk.stmts[i]->kind() == ast::Stmt::ExprStmt;
                if (tail)
                    out_ += pad() + "return ("
                          + expr(*static_cast<ast::ExprStmt&>(*blk.stmts[i]).expr) + ");\n";
                else
                    emit_stmt(*blk.stmts[i]);
            }
        } else if (l.expr_body) {
            sync_line(l.expr_body->line);
            out_ += pad() + "return (" + expr(*l.expr_body) + ");\n";
        }
        --indent_;
        std::swap(out_, buf);
        return header + " {\n" + buf + pad() + "}";
    }

    void emit_if_inline(ast::IfStmt& i)
    {
        out_ += "if (" + expr(*i.cond) + ") {\n";
        ++indent_;
        emit_body(*i.then_block);
        --indent_;
        if (i.else_block) {
            out_ += pad() + "} else ";
            if (i.else_block->kind() == ast::Stmt::If)
                emit_if_inline(static_cast<ast::IfStmt&>(*i.else_block));
            else {
                out_ += "{\n";
                ++indent_;
                emit_body(*i.else_block);
                --indent_;
                out_ += pad() + "}\n";
            }
        } else {
            out_ += pad() + "}\n";
        }
    }

    void emit_for(ast::ForStmt& f)
    {
        sync_line(f.line);
        if (f.is_range) {
            std::string end_name = "__cpp2_end_" + std::to_string(fresh_++);
            out_ += pad() + "{\n";
            ++indent_;
            out_ += pad() + "auto&& " + end_name + " = (" + expr(*f.range_end) + ");\n";
            out_ += pad() + "for (auto " + f.var + " = (" + expr(*f.range_begin) + "); "
                  + f.var + (f.inclusive ? " <= " : " < ") + end_name
                  + "; ++" + f.var + ") {\n";
            ++indent_;
            emit_body(*f.body);
            --indent_;
            out_ += pad() + "}\n";
            --indent_;
            out_ += pad() + "}\n";
        } else {
            out_ += pad() + "for (auto&& " + f.var + " : (" + expr(*f.iterable) + ")) {\n";
            ++indent_;
            emit_body(*f.body);
            --indent_;
            out_ += pad() + "}\n";
        }
    }

    // ── 声明 ───────────────────────────────────────────────────────
    // 泛型函数的 In 参数改发 "T const&":cpp2::in<T>(conditional_t)
    // 是不可推导上下文,模板实参无法从调用点推得(v0.1 偏差,见 IMPLEMENTATION)
    std::unordered_set<std::string> const* generic_params_ = nullptr;

    std::string param_str(ast::Param const& p, bool with_default)
    {
        std::string res;
        bool generic_in = p.mode == ast::ParamMode::In && generic_params_;
        switch (p.mode) {
        case ast::ParamMode::In:
            if (generic_in) res = type_str(p.type) + " const& " + p.name;
            else            res = "cpp2::in<" + type_str(p.type) + "> " + p.name;
            break;
        case ast::ParamMode::Inout:
        case ast::ParamMode::Out:     res = type_str(p.type) + "& " + p.name; break;
        case ast::ParamMode::Move:    res = type_str(p.type) + "&& " + p.name; break;
        case ast::ParamMode::Copy:    res = type_str(p.type) + " " + p.name; break;
        case ast::ParamMode::Forward: {
            // forward f: F(F 为本函数类型参数)→ "F&&"(转发引用,可推导);
            // 具体类型的 forward → auto&&
            bool tp = generic_params_ && p.type.parts.size() == 1
                   && generic_params_->count(p.type.parts[0]);
            res = (tp ? type_str(p.type) : std::string("auto")) + "&& " + p.name;
            break;
        }
        }
        if (with_default && p.default_value) res += " = " + expr(*p.default_value);
        return res;
    }

    std::string params_str(std::vector<ast::Param> const& ps, bool with_defaults)
    {
        std::string s;
        for (size_t i = 0; i < ps.size(); ++i) {
            if (i) s += ", ";
            s += param_str(ps[i], with_defaults);
        }
        return s;
    }

    // throws → cpp2::expected<R>(= std::expected<R, cpp2::error>,IMPL §4.3)
    std::string ret_type_str(std::optional<ast::TypeUse> const& ret, bool throws)
    {
        std::string rt = ret ? type_str(*ret) : "void";
        if (throws) rt = "cpp2::expected<" + rt + ">";
        return rt;
    }

    std::string signature(ast::FuncDecl& f, bool with_defaults)
    {
        std::string s;
        if (f.name == "main") s = "int main(";
        else if (!f.ret && !f.throws) s = "void " + f.name + "(";
        else                  s = "auto " + f.name + "(";
        s += params_str(f.params, with_defaults) + ")";
        if (f.name != "main" && (f.ret || f.throws))
            s += " -> " + ret_type_str(f.ret, f.throws);
        return s;
    }

    // 收集 post 契约中的 old(...) 节点 → 缓存变量名(发射顺序 = 遍历顺序,稳定)
    void collect_olds(ast::Expr& e, std::unordered_map<ast::Expr*, std::string>& out)
    {
        switch (e.kind()) {
        case ast::Expr::Literal:
        case ast::Expr::Name:
            return;
        case ast::Expr::Paren:
            return collect_olds(*static_cast<ast::ParenExpr&>(e).inner, out);
        case ast::Expr::Call: {
            auto& c = static_cast<ast::CallExpr&>(e);
            if (c.callee->kind() == ast::Expr::Name
                && static_cast<ast::NameExpr&>(*c.callee).parts.size() == 1
                && static_cast<ast::NameExpr&>(*c.callee).parts[0] == "old"
                && c.args.size() == 1) {
                out.emplace(&e, "__c2_old_" + std::to_string(fresh_++));
            }
            for (auto& a : c.args) collect_olds(*a, out);
            return;
        }
        case ast::Expr::Binary: {
            auto& b = static_cast<ast::BinaryExpr&>(e);
            collect_olds(*b.lhs, out);
            collect_olds(*b.rhs, out);
            return;
        }
        case ast::Expr::Unary:
            return collect_olds(*static_cast<ast::UnaryExpr&>(e).operand, out);
        case ast::Expr::Assign: {
            auto& a = static_cast<ast::AssignExpr&>(e);
            collect_olds(*a.target, out);
            collect_olds(*a.value, out);
            return;
        }
        case ast::Expr::Index: {
            auto& x = static_cast<ast::IndexExpr&>(e);
            collect_olds(*x.base, out);
            collect_olds(*x.index, out);
            return;
        }
        case ast::Expr::Member:
            return collect_olds(*static_cast<ast::MemberExpr&>(e).base, out);
        case ast::Expr::StructLit: {
            for (auto& [n, v] : static_cast<ast::StructLitExpr&>(e).fields)
                collect_olds(*v, out);
            return;
        }
        case ast::Expr::AsCast:
            return collect_olds(*static_cast<ast::AsCastExpr&>(e).operand, out);
        case ast::Expr::ListLit: {
            for (auto& el : static_cast<ast::ListLitExpr&>(e).elements)
                collect_olds(*el, out);
            return;
        }
        case ast::Expr::Try:
            return collect_olds(*static_cast<ast::TryExpr&>(e).operand, out);
        case ast::Expr::OrDefault: {
            auto& x = static_cast<ast::OrDefaultExpr&>(e);
            collect_olds(*x.lhs, out);
            collect_olds(*x.rhs, out);
            return;
        }
        case ast::Expr::Must:
            return collect_olds(*static_cast<ast::MustExpr&>(e).operand, out);
        case ast::Expr::Match: {
            auto& x = static_cast<ast::MatchExpr&>(e);
            collect_olds(*x.scrutinee, out);
            for (auto& arm : x.arms) {
                if (arm.guard) collect_olds(*arm.guard, out);
                if (arm.body) collect_olds_stmt(*arm.body, out);
            }
            return;
        }
        case ast::Expr::Lambda: {
            auto& l = static_cast<ast::LambdaExpr&>(e);
            for (auto& p : l.params)
                if (p.default_value) collect_olds(*p.default_value, out);
            if (l.expr_body) collect_olds(*l.expr_body, out);
            if (l.has_block_body && l.block_body)
                collect_olds_stmt(*l.block_body, out);
            return;
        }
        }
    }

    // 语句里的 old(...)(match 臂 / lambda 块体)
    void collect_olds_stmt(ast::Stmt& s,
                           std::unordered_map<ast::Expr*, std::string>& out)
    {
        switch (s.kind()) {
        case ast::Stmt::ExprStmt: {
            auto& x = static_cast<ast::ExprStmt&>(s);
            if (x.expr) collect_olds(*x.expr, out);
            return;
        }
        case ast::Stmt::Return: {
            auto& r = static_cast<ast::ReturnStmt&>(s);
            if (r.value) collect_olds(*r.value, out);
            return;
        }
        case ast::Stmt::Var: {
            auto& v = static_cast<ast::VarStmt&>(s);
            if (v.init) collect_olds(*v.init, out);
            return;
        }
        case ast::Stmt::If: {
            auto& i = static_cast<ast::IfStmt&>(s);
            if (i.cond) collect_olds(*i.cond, out);
            if (i.let_init) collect_olds(*i.let_init, out);
            if (i.then_block) collect_olds_stmt(*i.then_block, out);
            if (i.else_block) collect_olds_stmt(*i.else_block, out);
            return;
        }
        case ast::Stmt::Block: {
            for (auto& st : static_cast<ast::BlockStmt&>(s).stmts)
                collect_olds_stmt(*st, out);
            return;
        }
        default:
            return;
        }
    }

    // 函数体发射:无契约 = 原样;有契约 = old 入口缓存 → pre → 体(post 时
    // lambda 包裹)→ post 检查(DESIGN §6.5,IMPL §4.4)。
    // throws 函数的 lambda 返回 expected('?'/return R 同型直达出口);
    // 非 throws 函数返回 R 本身——失败只可能来自 trap,不存在错误传播。
    void emit_body_of(std::string const& name, bool throws, ast::Expr* pre, ast::Expr* post,
                      bool has_block, ast::Stmt* block, ast::Expr* body_expr,
                      std::optional<ast::TypeUse> const& ret, int line,
                      ast::Expr* inv = nullptr, int inv_line = 0,
                      std::string const& inv_label = "")
    {
        ++indent_;
        bool returns = ret.has_value() && type_str(*ret) != "void";
        // §6.7:Release 关 post/old(廉价断言 pre/invariant 保留)
        ast::Expr* epost = release_ ? nullptr : post;
        bool has_exit = epost || inv;

        if (!pre && !has_exit) {               // 快路径:零额外代码
            emit_body_core(has_block, block, body_expr, ret, line);
            --indent_;
            return;
        }

        // old() 入口缓存(post 中的 old(expr) 在函数入口求值并暂存)
        std::unordered_map<ast::Expr*, std::string> olds;
        if (epost) collect_olds(*epost, olds);
        for (auto& [call, var] : olds) {
            auto& oc = static_cast<ast::CallExpr&>(*call);
            sync_line(oc.line);
            out_ += pad() + "auto " + var + " = (" + expr(*oc.args[0]) + ");\n";
        }

        if (pre) {                             // pre:违反 = bug → trap,不可捕获
            sync_line(pre->line);
            out_ += pad() + "if (!(" + expr(*pre) + ")) { cpp2::trap(\"precondition failed: "
                  + name + "\"" + check_loc(pre->line) + "); }\n";
        }

        if (inv) {                             // invariant 入口(DESIGN §6.5)
            sync_line(inv_line);
            out_ += pad() + "if (!(" + expr(*inv) + ")) { cpp2::trap(\"invariant violated: "
                  + (inv_label.empty() ? std::string(name) : inv_label) +  "\"" + check_loc(inv_line) + "); }\n";
        }

        if (!has_exit) {
            emit_body_core(has_block, block, body_expr, ret, line);
            --indent_;
            return;
        }

        if (returns) {
            // 体包进 lambda:return R 隐式转 expected;'?' 传播同型直达出口
            std::string lt = throws ? "cpp2::expected<" + type_str(*ret) + ">"
                                    : type_str(*ret);
            out_ += pad() + "auto __c2_result = [&]() -> " + lt + " {\n";
            ++indent_;
            emit_body_core(has_block, block, body_expr, ret, line);
            --indent_;
            out_ += pad() + "}();\n";
            if (throws)
                out_ += pad() + "if (!__c2_result) { return __c2_result; }\n";
            if (inv) {                         // 出口:先不变量后 post
                sync_line(inv_line);
                out_ += pad() + "if (!(" + expr(*inv) + ")) { cpp2::trap(\"invariant violated: "
                      + (inv_label.empty() ? std::string(name) : inv_label) +  "\"" + check_loc(inv_line) + "); }\n";
            }
            if (epost) {
                old_names_ = &olds;
                in_post_ = true;
                result_wrapped_ = throws;
                sync_line(epost->line);
                out_ += pad() + "if (!(" + expr(*epost) + ")) { cpp2::trap(\"postcondition failed: "
                      + name + "\"" + check_loc(epost->line) + "); }\n";
                in_post_ = false;
                old_names_ = nullptr;
            }
            out_ += pad() + "return __c2_result;\n";
        } else {
            out_ += pad() + "[&] {\n";
            ++indent_;
            emit_body_core(has_block, block, body_expr, ret, line);
            --indent_;
            out_ += pad() + "}();\n";
            if (inv) {
                sync_line(inv_line);
                out_ += pad() + "if (!(" + expr(*inv) + ")) { cpp2::trap(\"invariant violated: "
                      + (inv_label.empty() ? std::string(name) : inv_label) +  "\"" + check_loc(inv_line) + "); }\n";
            }
            if (epost) {
                old_names_ = &olds;
                in_post_ = true;
                sync_line(epost->line);
                out_ += pad() + "if (!(" + expr(*epost) + ")) { cpp2::trap(\"postcondition failed: "
                      + name + "\"" + check_loc(epost->line) + "); }\n";
                in_post_ = false;
                old_names_ = nullptr;
            }
        }
        --indent_;
    }

    void emit_body_core(bool has_block, ast::Stmt* block, ast::Expr* body_expr,
                        std::optional<ast::TypeUse> const& ret, int line)
    {
        if (has_block && block) {
            emit_body(*block);
        } else if (body_expr) {
            bool returns = ret.has_value() && type_str(*ret) != "void";
            if (body_expr->kind() == ast::Expr::Try) {
                // 短体 f: () -> R throws = g()?;:失败提前 return unexpected
                sync_line(line);
                std::string tmp = emit_try_core(static_cast<ast::TryExpr&>(*body_expr));
                out_ += pad() + (returns ? "return *std::move(" + tmp + ");"
                                         : "(void)(" + tmp + ");") + "\n";
                return;
            }
            sync_line(line);
            // match 值经 expr() 提升为语句(见 emit_match_value),此处消费变量
            out_ += pad() + (returns ? "return " : "(void)(")
                  + expr(*body_expr) + (returns ? ";\n" : ");\n");
        }
    }

    // 泛型模板头:template <class T, ...> requires Ordered<T> && ...(DESIGN §5.6)
    std::string template_header(ast::FuncDecl& f)
    {
        std::string s = "template <";
        for (size_t i = 0; i < f.type_params.size(); ++i) {
            if (i) s += ", ";
            s += "class " + f.type_params[i].name;
        }
        s += ">";
        std::string reqs;
        auto join_parts = [](std::vector<std::string> const& parts) {
            std::string r;
            for (size_t i = 0; i < parts.size(); ++i)
                r += (i ? "::" : "") + parts[i];
            return r;
        };
        for (auto& tp : f.type_params) {
            if (tp.concept_parts.empty()) continue;
            if (!reqs.empty()) reqs += " && ";
            reqs += join_parts(tp.concept_parts) + "<" + tp.name + ">";
        }
        for (auto& r : f.requires_list) {
            if (!reqs.empty()) reqs += " && ";
            reqs += join_parts(r.name_parts);
            if (!r.args.empty()) {
                reqs += "<";
                for (size_t i = 0; i < r.args.size(); ++i) {
                    if (i) reqs += ", ";
                    reqs += r.args[i];
                }
                reqs += ">";
            }
        }
        if (!reqs.empty()) s += " requires " + reqs;
        return s;
    }

    void emit_prototype(ast::FuncDecl& f, std::string const& prefix = "")
    {
        sync_line(f.line);
        // builtin 原语:无原型(调用点由 emit_call 按表降到 rt/后端实现)
        if (f.builtin) return;
        // 无体声明分两类:
        //   extern "C" 前缀(c_linkage)→ C 链接裸参数,链接期由系统 CRT/OS 解析
        //   普通无体声明 → C++ 链接原型,与 cxx_legacy 块内定义配对(M6)
        if (f.is_extern && f.c_linkage) {
            std::string rt = f.ret ? type_str(*f.ret) : "void";
            std::string ps;
            for (size_t i = 0; i < f.params.size(); ++i) {
                if (i) ps += ", ";
                ps += type_str(f.params[i].type) + " " + f.params[i].name;
            }
            out_ += prefix + "extern \"C\" " + rt + " " + f.name + "(" + ps + ");\n";
            return;
        }
        std::unordered_set<std::string> tp;
        for (auto& t : f.type_params) tp.insert(t.name);
        generic_params_ = f.type_params.empty() ? nullptr : &tp;
        if (!f.type_params.empty())
            out_ += prefix + template_header(f) + "\n";
        // 无返回类型的原型用 void(auto 会成为推导返回类型,
        // extern 声明在定义可见前不可用); throws void → expected<void>
        if (!f.ret && !f.throws)
            out_ += prefix + "void " + f.name + "(" + params_str(f.params, /*with_defaults*/true) + ");\n";
        else
            out_ += prefix + signature(f, /*with_defaults*/true) + ";\n";
        generic_params_ = nullptr;
    }

    void emit_definition(ast::FuncDecl& f)
    {
        if (f.is_extern) return;               // 无体声明:仅原型(M6 互操作)
        sync_line(f.line);
        std::unordered_set<std::string> tp;
        for (auto& t : f.type_params) tp.insert(t.name);
        generic_params_ = f.type_params.empty() ? nullptr : &tp;
        if (!f.type_params.empty())
            out_ += template_header(f) + "\n";
        out_ += signature(f, /*with_defaults*/false) + "\n{\n";
        if (f.name == "main") {
            // M6:GC 栈顶锚点——锚变量在 main 帧内,覆盖全部调用帧
            out_ += pad() + "char __c2_gc_top;\n";
            out_ += pad() + "cpp2::gc_set_stack_top(&__c2_gc_top);\n";
        }
        emit_body_of(f.name, f.throws, f.pre.get(), f.post.get(),
                     f.has_block_body, f.block_body.get(), f.expr_body.get(), f.ret, f.line);
        out_ += "}\n\n";
        generic_params_ = nullptr;
    }

    void emit_global(ast::GlobalVar& g, std::string const& prefix = "")
    {
        sync_line(g.line);
        std::string type = g.has_type ? type_str(g.type)
                          : (g.is_const ? "auto const" : "auto");
        out_ += prefix + type + " " + g.name
              + (g.init ? " = " + expr(*g.init) : "") + ";\n";
    }

    void emit_enum(ast::EnumDecl& e, std::string const& prefix = "")
    {
        sync_line(e.line);
        out_ += prefix + "enum class " + e.name;
        if (e.underlying) out_ += " : " + type_str(*e.underlying);
        out_ += " { ";
        for (size_t i = 0; i < e.members.size(); ++i) {
            if (i) out_ += ", ";
            out_ += e.members[i];
        }
        out_ += " };\n";
    }

    // Value: variant = { int, string } → using Value = std::variant<int, std::string>;
    // (DESIGN §5.5:类型安全联合,match 是唯一合法访问)
    void emit_variant(ast::VariantDecl& v, std::string const& prefix = "")
    {
        sync_line(v.line);
        out_ += prefix + "using " + v.name + " = std::variant<";
        for (size_t i = 0; i < v.alternatives.size(); ++i) {
            if (i) out_ += ", ";
            out_ += type_str(v.alternatives[i]);
        }
        out_ += ">;\n";
    }

    // Ordered: concept = { operator<: (that: self) -> bool; } →
    // template <class __c2_Self> concept Ordered = requires(__c2_Self __c2_s) {
    //     __c2_s < __c2_s; };  (DESIGN §5.6;满足性判定委托 C++20 concept)
    static std::string op_symbol(std::string const& name)
    {
        if (name == "operator<")  return "<";
        if (name == "operator>")  return ">";
        if (name == "operator<=") return "<=";
        if (name == "operator>=") return ">=";
        if (name == "operator==") return "==";
        if (name == "operator!=") return "!=";
        if (name == "operator+")  return "+";
        if (name == "operator-")  return "-";
        if (name == "operator*")  return "*";
        if (name == "operator/")  return "/";
        return "";
    }

    void emit_concept(ast::ConceptDecl& c, std::string const& prefix = "")
    {
        auto is_self = [](ast::TypeUse const& tu) {
            return tu.parts.size() == 1 && tu.parts[0] == "self";
        };
        auto operand = [&](ast::Param const& p) {
            return is_self(p.type) ? std::string("__c2_s")
                                   : "std::declval<" + type_str(p.type) + ">()";
        };
        sync_line(c.line);
        out_ += prefix + "template <class __c2_Self>\n"
              + prefix + "concept " + c.name + " = requires(__c2_Self __c2_s) {\n";
        ++indent_;
        for (auto& req : c.reqs) {
            sync_line(req.line);
            if (std::string op = op_symbol(req.name); !op.empty()) {
                std::string rhs = "__c2_s";
                if (req.params.size() >= 2) rhs = operand(req.params[1]);
                out_ += pad() + "__c2_s " + op + " " + rhs + ";\n";
            } else {
                std::string args;
                for (size_t i = 0; i < req.params.size(); ++i) {
                    if (i) args += ", ";
                    args += operand(req.params[i]);
                }
                out_ += pad() + "__c2_s." + req.name + "(" + args + ");\n";
            }
        }
        --indent_;
        out_ += "};\n";
    }

    void emit_struct(ast::StructDecl& s, std::string const& prefix = "")
    {
        sync_line(s.line);
        out_ += prefix + "struct " + s.name;
        if (s.base) out_ += " : public " + type_str(*s.base);
        out_ += " {\n";
        ++indent_;
        for (auto& f : s.fields) {
            sync_line(f.line);
            out_ += pad() + type_str(f.type) + " " + f.name + " = " + expr(*f.init) + ";\n";
        }
        --indent_;
        for (auto& md : s.methods) emit_method(s, md);
        // 有虚方法的类型:自动合成 virtual 析构(经基指针 delete 安全)
        bool has_virt = false;
        for (auto& md : s.methods) has_virt = has_virt || md.is_virtual;
        if (has_virt && !s.find_method("destructor"))
            out_ += pad() + "virtual ~" + s.name + "() = default;\n";
        out_ += "};\n";
    }

    void emit_method(ast::StructDecl& s, ast::MethodDecl& md)
    {
        sync_line(md.line);
        out_ += "\n";
        if (md.name == "destructor") {
            bool vdtor = md.is_virtual || s.needs_virtual_dtor;
            out_ += pad() + (vdtor ? "virtual " : "") + "~" + s.name + "()\n{\n";
            emit_body_of(md.name, false, nullptr, nullptr,
                         md.has_block_body, md.block_body.get(), md.expr_body.get(),
                         std::nullopt, md.line);
            out_ += pad() + "}\n";
            return;
        }
        std::string sig = "auto " + md.name + "(" + params_str(md.params, false) + ")";
        if (md.is_virtual) sig = "virtual " + sig;
        if (!md.uses_members) sig = "static " + sig;
        else if (!md.mutates) sig += " const";
        if (md.ret) sig += " -> " + ret_type_str(md.ret, md.throws);
        // invariant:仅注入引用成员的方法(静态方法无对象;析构器跳过)
        bool guarded = md.uses_members && s.invariant;
        out_ += pad() + sig + "\n" + pad() + "{\n";
        emit_body_of(md.name, md.throws, md.pre.get(), md.post.get(),
                     md.has_block_body, md.block_body.get(), md.expr_body.get(), md.ret, md.line,
                     guarded ? s.invariant.get() : nullptr,
                     guarded ? s.invariant_line : 0,
                     guarded ? s.name : "");
        out_ += pad() + "}\n";
    }

    // ── headers 后端辅助:声明式结构体 / inline 全局 / 线外方法定义 ──
    void emit_struct_header(ast::StructDecl& s)
    {
        sync_line(s.line);
        out_ += "struct " + s.name;
        if (s.base) out_ += " : public " + type_str(*s.base);
        out_ += " {\n";
        ++indent_;
        for (auto& f : s.fields) {
            sync_line(f.line);
            out_ += pad() + type_str(f.type) + " " + f.name + " = " + expr(*f.init) + ";\n";
        }
        --indent_;
        for (auto& md : s.methods) {
            sync_line(md.line);
            if (md.name == "destructor") {
                bool vdtor = md.is_virtual || s.needs_virtual_dtor;
                out_ += pad() + (vdtor ? "virtual " : "") + "~" + s.name + "();\n";
                continue;
            }
            std::string sig = "auto " + md.name + "("
                            + params_str(md.params, /*with_defaults*/true) + ")";
            if (md.is_virtual) sig = "virtual " + sig;
            if (!md.uses_members) sig = "static " + sig;
            else if (!md.mutates) sig += " const";
            if (md.ret) sig += " -> " + ret_type_str(md.ret, md.throws);
            out_ += pad() + sig + ";\n";
        }
        // 有虚方法的类型:自动合成 virtual 析构声明
        bool has_virt_hdr = false;
        for (auto& md : s.methods) has_virt_hdr = has_virt_hdr || md.is_virtual;
        if (has_virt_hdr && !s.find_method("destructor"))
            out_ += pad() + "virtual ~" + s.name + "() = default;\n";
        out_ += "};\n";
    }

    void emit_global_header(ast::GlobalVar& g)
    {
        sync_line(g.line);
        std::string type = g.has_type ? type_str(g.type)
                          : (g.is_const ? "auto const" : "auto");
        out_ += "inline " + type + " " + g.name
              + (g.init ? " = " + expr(*g.init) : "") + ";\n";
    }

    void emit_method_def(ast::StructDecl& s, ast::MethodDecl& md)
    {
        sync_line(md.line);
        if (md.name == "destructor") {
            out_ += s.name + "::~" + s.name + "()\n{\n";
            emit_body_of(md.name, false, nullptr, nullptr,
                         md.has_block_body, md.block_body.get(), md.expr_body.get(),
                         std::nullopt, md.line);
            out_ += "}\n\n";
            return;
        }
        std::string sig = "auto " + s.name + "::" + md.name + "("
                        + params_str(md.params, /*with_defaults*/false) + ")";
        if (md.uses_members && !md.mutates) sig += " const";
        if (md.ret) sig += " -> " + ret_type_str(md.ret, md.throws);
        bool guarded = md.uses_members && s.invariant;   // invariant 出入口注入
        out_ += sig + "\n{\n";
        emit_body_of(md.name, md.throws, md.pre.get(), md.post.get(),
                     md.has_block_body, md.block_body.get(), md.expr_body.get(), md.ret, md.line,
                     guarded ? s.invariant.get() : nullptr,
                     guarded ? s.invariant_line : 0,
                     guarded ? s.name : "");
        out_ += "}\n\n";
    }
};

} // namespace

std::string emit_flatten(std::vector<ModuleEntry> const& units, bool release)
{
    std::string out = "// Generated by cpp2c (whole-program flatten). DO NOT EDIT.\n"
                      + prelude_includes() + "\n";

    for (auto const& e : units) {
        Emitter em;
        em.set(*e.m, *e.r, e.src_name);
        em.set_release(release);
        out += em.legacy_text();               // cxx_legacy:全局域,先于命名空间
        out += em.flatten_block();
        out += em.flatten_usings(e.is_root);
        out += "\n";
    }
    for (auto const& e : units) {
        if (!e.is_root) continue;
        Emitter em;
        em.set(*e.m, *e.r, e.src_name);
        em.set_release(release);
        out += em.main_definition();
    }
    return out;
}

std::string emit_module_unit(ModuleEntry const& e, bool release)
{
    Emitter em;
    em.set(*e.m, *e.r, e.src_name);
    em.set_release(release);
    return em.module_unit(e);
}

std::pair<std::string, std::string> emit_headers(ModuleEntry const& e, bool release)
{
    Emitter em;
    em.set(*e.m, *e.r, e.src_name);
    em.set_release(release);
    std::string h = em.headers_header(e.imports);
    std::string cpp = em.headers_impl(e.is_root);
    return {h, cpp};
}

std::pair<std::string, std::string> emit_bridge(std::vector<ModuleEntry> const& units,
                                                std::string const& libname)
{
    std::string h;    // banner/include 由 bridge_header/bridge_impl 各自生成一次
    std::string cpp;

    for (auto const& e : units) {
        Emitter em;
        em.set(*e.m, *e.r, e.src_name);
        h += em.bridge_header(libname);
        cpp += em.bridge_impl(libname);
    }
    return {h, cpp};
}

} // namespace cpp2::emit
