// C++2 → C++23 发射器实现(M2b:检查注入、类型/枚举、方法、智能指针)
#include "emit.hpp"

#include <unordered_map>
#include <unordered_set>

namespace cpp2::emit {

namespace {

int bin_prec(std::string const& op)
{
    if (op == "||") return 1;
    if (op == "&&") return 2;
    if (op == "==" || op == "!=") return 3;
    if (op == "<" || op == ">" || op == "<=" || op == ">=") return 4;
    if (op == "+" || op == "-") return 5;
    if (op == "*" || op == "/" || op == "%") return 6;
    return 0;
}

int expr_prec(ast::Expr& e)
{
    switch (e.kind()) {
    case ast::Expr::Binary: return bin_prec(static_cast<ast::BinaryExpr&>(e).op);
    case ast::Expr::Unary:  return 7;
    default:                return 8;
    }
}

std::string escape_path(std::string p)
{
    std::string out;
    for (char c : p) {
        if (c == '\\') out += '/';
        else if (c == '"') out += "\\\"";
        else out += c;
    }
    return out;
}

class Emitter {
public:
    Emitter(ast::Module& m, sema::Result const& sema, std::string src)
        : m_(m), sema_(sema), src_(escape_path(std::move(src))) {}

    std::string run()
    {
        out_ += "// Generated by cpp2c from '" + src_ + "'. DO NOT EDIT.\n";
        out_ += "#include \"cpp2/support.hpp\"\n";
        out_ += "#include <cmath>\n";
        out_ += "#include <cstdint>\n";
        out_ += "#include <string>\n";
        out_ += "#include <utility>\n";
        out_ += "#include <vector>\n";
        out_ += "\n";

        for (auto& e : m_.enums)   emit_enum(e);
        for (auto& s : m_.structs) emit_struct(s);
        for (auto& g : m_.globals) emit_global(g);
        for (auto& f : m_.funcs) {
            if (f.name != "main") emit_prototype(f);   // main 不出原型
        }
        out_ += "\n";
        for (auto& f : m_.funcs) emit_definition(f);
        return std::move(out_);
    }

private:
    ast::Module& m_;
    sema::Result const& sema_;
    std::string src_;
    std::string out_;
    int indent_ = 0;
    int last_line_ = -1;
    int fresh_ = 0;
    bool checks_on_ = true;

    sema::Type type_of(ast::Expr& e) const { return sema_.type_of(e); }

    // ── 类型与名字映射(IMPL §4.7 stdbridge)───────────────────────
    static std::string map_type_name(std::string const& n)
    {
        static std::unordered_map<std::string, std::string> const map{
            {"int", "int"}, {"double", "double"}, {"float", "float"},
            {"bool", "bool"}, {"void", "void"}, {"char", "char"},
            {"i8", "std::int8_t"}, {"i16", "std::int16_t"},
            {"i32", "std::int32_t"}, {"i64", "std::int64_t"},
            {"u8", "std::uint8_t"}, {"u16", "std::uint16_t"},
            {"u32", "std::uint32_t"}, {"u64", "std::uint64_t"},
            {"string", "std::string"}, {"string_view", "std::string_view"},
            {"list", "std::vector"}, {"vector", "std::vector"},
            {"byte", "std::byte"},
            {"unique", "std::unique_ptr"}, {"shared", "std::shared_ptr"},
            {"weak", "std::weak_ptr"},
        };
        auto it = map.find(n);
        return it != map.end() ? it->second : n;
    }

    std::string type_str(ast::TypeUse const& t)
    {
        if (t.parts.empty()) return "void";
        std::string s = map_type_name(t.parts[0]);
        for (size_t i = 1; i < t.parts.size(); ++i) s += "::" + t.parts[i];
        if (!t.args.empty()) {
            s += "<";
            for (size_t i = 0; i < t.args.size(); ++i) {
                if (i) s += ", ";
                s += type_str(t.args[i]);
            }
            s += ">";
        }
        if (t.is_const) s += " const";
        return s;
    }

    std::string name_expr_str(ast::NameExpr& n)
    {
        if (n.parts.size() == 2 && n.parts[0] == "std") {
            if (n.parts[1] == "print" || n.parts[1] == "println")
                return "cpp2::stdx::" + n.parts[1];
            return "std::" + n.parts[1];
        }
        if (n.parts.size() == 1
            && (n.parts[0] == "make_unique" || n.parts[0] == "make_shared"))
            return "cpp2::" + n.parts[0];
        std::string s = n.parts[0];
        for (size_t i = 1; i < n.parts.size(); ++i) s += "::" + n.parts[i];
        return s;
    }

    // 检查调用附带的定位参数:"文件", 行
    std::string check_loc(int line) const
    {
        return ", \"" + src_ + "\", " + std::to_string(line);
    }

    // sema 类型 → C++ 类型名(检查调用需要统一操作数类型)
    static std::string cpp_type_of(sema::Type const& t)
    {
        switch (t.kind) {
        case sema::Type::Int:  return "int";
        case sema::Type::I8:   return "std::int8_t";
        case sema::Type::I16:  return "std::int16_t";
        case sema::Type::I32:  return "std::int32_t";
        case sema::Type::I64:  return "std::int64_t";
        case sema::Type::U8:   return "std::uint8_t";
        case sema::Type::U16:  return "std::uint16_t";
        case sema::Type::U32:  return "std::uint32_t";
        case sema::Type::U64:  return "std::uint64_t";
        default:               return "int";
        }
    }

    // checked_<op>(l, r) 统一到结果类型:static_cast 免转换成本
    std::string checked_call(std::string const& fn, ast::Expr& l, ast::Expr& r,
                             sema::Type const& res, int line)
    {
        std::string t = cpp_type_of(res);
        return "cpp2::" + fn + "(static_cast<" + t + ">(" + expr(l)
             + "), static_cast<" + t + ">(" + expr(r) + ")" + check_loc(line) + ")";
    }

    // ── 表达式 ─────────────────────────────────────────────────────
    std::string expr(ast::Expr& e)
    {
        switch (e.kind()) {
        case ast::Expr::Literal:
            return static_cast<ast::LiteralExpr&>(e).text;
        case ast::Expr::Name:
            return name_expr_str(static_cast<ast::NameExpr&>(e));
        case ast::Expr::Paren:
            return "(" + expr(*static_cast<ast::ParenExpr&>(e).inner) + ")";
        case ast::Expr::Call: {
            auto& c = static_cast<ast::CallExpr&>(e);
            std::string s = expr(*c.callee) + "(";
            for (size_t i = 0; i < c.args.size(); ++i) {
                if (i) s += ", ";
                s += expr(*c.args[i]);
            }
            return s + ")";
        }
        case ast::Expr::Binary: {
            auto& b = static_cast<ast::BinaryExpr&>(e);

            // 检查注入:有符号 + - * / % → checked_*(DESIGN §6.3)
            if (checks_on_ && (b.op == "+" || b.op == "-" || b.op == "*"
                            || b.op == "/" || b.op == "%")) {
                sema::Type l = type_of(*b.lhs), r = type_of(*b.rhs);
                if (l.is_signed() && r.is_signed()) {
                    std::string fn = b.op == "+" ? "checked_add"
                                  : b.op == "-" ? "checked_sub"
                                  : b.op == "*" ? "checked_mul"
                                  : b.op == "/" ? "checked_div"
                                                : "checked_mod";
                    return checked_call(fn, *b.lhs, *b.rhs, type_of(b), b.line);
                }
            }

            int p = bin_prec(b.op);
            std::string l = expr(*b.lhs);
            std::string r = expr(*b.rhs);
            if (expr_prec(*b.lhs) < p) l = "(" + l + ")";
            if (expr_prec(*b.rhs) <= p && b.rhs->kind() == ast::Expr::Binary) r = "(" + r + ")";
            return l + " " + b.op + " " + r;
        }
        case ast::Expr::Unary: {
            auto& u = static_cast<ast::UnaryExpr&>(e);
            if (u.op == "move")                       // 调用侧显式 move → std::move
                return "std::move(" + expr(*u.operand) + ")";
            std::string s = expr(*u.operand);
            if (expr_prec(*u.operand) < 7) s = "(" + s + ")";
            return u.op + s;
        }
        case ast::Expr::Assign: {
            auto& a = static_cast<ast::AssignExpr&>(e);
            return expr(*a.target) + " " + a.op + " " + expr(*a.value);
        }
        case ast::Expr::Index: {
            auto& x = static_cast<ast::IndexExpr&>(e);
            sema::Type b = type_of(*x.base);

            // 检查注入:可下标类型 → cpp2::index(DESIGN §6.2)
            if (checks_on_ && b.is_indexable()) {
                return "cpp2::index(" + expr(*x.base) + ", " + expr(*x.index)
                     + check_loc(x.line) + ")";
            }
            std::string s = expr(*x.base);
            if (expr_prec(*x.base) < 8) s = "(" + s + ")";
            return s + "[" + expr(*x.index) + "]";
        }
        case ast::Expr::Member: {
            auto& x = static_cast<ast::MemberExpr&>(e);
            sema::Type b = type_of(*x.base);
            std::string s = expr(*x.base);
            if (expr_prec(*x.base) < 8) s = "(" + s + ")";
            // 智能指针 . 自动解引用(IMPL §4.6)
            return s + (b.is_smart() ? "->" : ".") + x.name;
        }
        case ast::Expr::StructLit: {
            auto& l = static_cast<ast::StructLitExpr&>(e);
            std::string name = map_type_name(l.type_parts[0]);
            for (size_t i = 1; i < l.type_parts.size(); ++i) name += "::" + l.type_parts[i];

            // 按字段声明顺序重排(C++20 designated initializers 要求声明序)
            std::vector<std::pair<std::string, ast::Expr*>> ordered;
            if (l.type_parts.size() == 1) {
                if (auto* sd = m_.find_struct(l.type_parts[0])) {
                    for (auto* f : fields_of(*sd)) {
                        for (auto& [fn, fv] : l.fields)
                            if (fn == f->name) ordered.push_back({fn, fv.get()});
                    }
                }
            }
            if (ordered.empty())
                for (auto& [fn, fv] : l.fields) ordered.push_back({fn, fv.get()});

            std::string s = name + "{";
            for (size_t i = 0; i < ordered.size(); ++i) {
                if (i) s += ", ";
                s += "." + ordered[i].first + " = " + expr(*ordered[i].second);
            }
            return s + "}";
        }
        case ast::Expr::AsCast: {
            auto& x = static_cast<ast::AsCastExpr&>(e);
            sema::Type src = type_of(*x.operand);
            sema::Type dst = type_from_target(x.target);
            std::string inner = expr(*x.operand);
            if (expr_prec(*x.operand) < 8) inner = "(" + inner + ")";
            std::string t = type_str(x.target);
            if (checks_on_ && src.is_arith() && dst.is_arith())
                return "cpp2::narrow_cast<" + t + ">(" + inner + check_loc(x.line) + ")";
            return "static_cast<" + t + ">(" + inner + ")";
        }
        case ast::Expr::ListLit: {
            auto& l = static_cast<ast::ListLitExpr&>(e);
            std::string s = "std::vector{";
            for (size_t i = 0; i < l.elements.size(); ++i) {
                if (i) s += ", ";
                s += expr(*l.elements[i]);
            }
            return s + "}";
        }
        }
        return "/*?*/";
    }

    sema::Type type_from_target(ast::TypeUse const& tu)
    {
        // 轻量复用:发射侧只需判算术性
        std::string n = tu.parts.back();
        sema::Type t;
        if (n == "int" || n == "i8" || n == "i16" || n == "i32" || n == "i64"
         || n == "int32_t" || n == "int64_t") t.kind = sema::Type::Int;
        else if (n == "u8" || n == "u16" || n == "u32" || n == "u64"
              || n == "uint32_t" || n == "uint64_t") t.kind = sema::Type::U32;
        else if (n == "double" || n == "float") t.kind = sema::Type::Double;
        else if (n == "bool") t.kind = sema::Type::Bool;
        else if (n == "char") t.kind = sema::Type::Char;
        return t;
    }

    std::vector<ast::FieldDecl*> fields_of(ast::StructDecl& s)
    {
        std::vector<ast::FieldDecl*> out;
        if (s.base && s.base->parts.size() == 1)
            if (auto* b = m_.find_struct(s.base->parts[0])) {
                auto base_fields = fields_of(*b);
                out.insert(out.end(), base_fields.begin(), base_fields.end());
            }
        for (auto& f : s.fields) out.push_back(&f);
        return out;
    }

    // ── 语句 ───────────────────────────────────────────────────────
    std::string pad() const { return std::string(indent_ * 4, ' '); }

    void sync_line(int line)
    {
        if (line > 0 && line != last_line_) {
            out_ += "#line " + std::to_string(line) + " \"" + src_ + "\"\n";
            last_line_ = line;
        }
    }

    // 已开块的体:Block 直接展开内部语句,避免双重花括号
    void emit_body(ast::Stmt& s)
    {
        if (s.kind() == ast::Stmt::Block) {
            for (auto& st : static_cast<ast::BlockStmt&>(s).stmts) emit_stmt(*st);
        } else {
            emit_stmt(s);
        }
    }

    void emit_stmt(ast::Stmt& s)
    {
        bool prev_checks = checks_on_;
        checks_on_ = checks_on_ && !s.no_check;

        switch (s.kind()) {
        case ast::Stmt::ExprStmt: {
            auto& x = static_cast<ast::ExprStmt&>(s);
            if (x.expr->kind() == ast::Expr::Assign) {
                auto& a = static_cast<ast::AssignExpr&>(*x.expr);
                sync_line(s.line);

                // 复合赋值检查注入:total += i → checked_add
                if (a.op != "=" && checks_on_) {
                    sema::Type t = type_of(*a.target);
                    if (t.is_signed()) {
                        std::string fn = a.op == "+=" ? "checked_add"
                                       : a.op == "-=" ? "checked_sub"
                                       : a.op == "*=" ? "checked_mul"
                                       : a.op == "/=" ? "checked_div"
                                                      : "checked_mod";
                        // 注意:复杂 target 会被求值两次(v[i] += x 场景),M2c 改临时变量
                        std::string target = expr(*a.target);
                        out_ += pad() + target + " = "
                              + checked_call(fn, *a.target, *a.value, t, a.line) + ";\n";
                        break;
                    }
                }
                out_ += pad() + expr(*x.expr) + ";\n";
            } else {
                sync_line(s.line);
                out_ += pad() + "(void)(" + expr(*x.expr) + ");\n";
            }
            break;
        }
        case ast::Stmt::Return: {
            auto& r = static_cast<ast::ReturnStmt&>(s);
            sync_line(s.line);
            out_ += pad() + (r.value ? "return " + expr(*r.value) + ";\n" : "return;\n");
            break;
        }
        case ast::Stmt::Var: {
            auto& v = static_cast<ast::VarStmt&>(s);
            sync_line(s.line);
            std::string type = v.has_type ? type_str(v.type)
                              : (v.is_const ? "auto const" : "auto");
            out_ += pad() + type + " " + v.name + " = " + expr(*v.init) + ";\n";
            break;
        }
        case ast::Stmt::If: {
            auto& i = static_cast<ast::IfStmt&>(s);
            sync_line(s.line);
            out_ += pad() + "if (" + expr(*i.cond) + ") {\n";
            ++indent_;
            emit_body(*i.then_block);
            --indent_;
            if (i.else_block) {
                out_ += pad() + "} else ";
                if (i.else_block->kind() == ast::Stmt::If)
                    emit_if_inline(static_cast<ast::IfStmt&>(*i.else_block));
                else {
                    out_ += "{\n";
                    ++indent_;
                    emit_body(*i.else_block);
                    --indent_;
                    out_ += pad() + "}\n";
                }
            } else {
                out_ += pad() + "}\n";
            }
            break;
        }
        case ast::Stmt::While: {
            auto& w = static_cast<ast::WhileStmt&>(s);
            sync_line(s.line);
            out_ += pad() + "while (" + expr(*w.cond) + ") {\n";
            ++indent_;
            emit_body(*w.body);
            --indent_;
            out_ += pad() + "}\n";
            break;
        }
        case ast::Stmt::For: {
            emit_for(static_cast<ast::ForStmt&>(s));
            break;
        }
        case ast::Stmt::Break:    sync_line(s.line); out_ += pad() + "break;\n"; break;
        case ast::Stmt::Continue: sync_line(s.line); out_ += pad() + "continue;\n"; break;
        case ast::Stmt::Block: {
            auto& b = static_cast<ast::BlockStmt&>(s);
            sync_line(s.line);
            out_ += pad() + "{\n";
            ++indent_;
            for (auto& st : b.stmts) emit_stmt(*st);
            --indent_;
            out_ += pad() + "}\n";
            break;
        }
        }

        checks_on_ = prev_checks;
    }

    void emit_if_inline(ast::IfStmt& i)
    {
        out_ += "if (" + expr(*i.cond) + ") {\n";
        ++indent_;
        emit_body(*i.then_block);
        --indent_;
        if (i.else_block) {
            out_ += pad() + "} else ";
            if (i.else_block->kind() == ast::Stmt::If)
                emit_if_inline(static_cast<ast::IfStmt&>(*i.else_block));
            else {
                out_ += "{\n";
                ++indent_;
                emit_body(*i.else_block);
                --indent_;
                out_ += pad() + "}\n";
            }
        } else {
            out_ += pad() + "}\n";
        }
    }

    void emit_for(ast::ForStmt& f)
    {
        sync_line(f.line);
        if (f.is_range) {
            std::string end_name = "__cpp2_end_" + std::to_string(fresh_++);
            out_ += pad() + "{\n";
            ++indent_;
            out_ += pad() + "auto&& " + end_name + " = (" + expr(*f.range_end) + ");\n";
            out_ += pad() + "for (auto " + f.var + " = (" + expr(*f.range_begin) + "); "
                  + f.var + (f.inclusive ? " <= " : " < ") + end_name
                  + "; ++" + f.var + ") {\n";
            ++indent_;
            emit_body(*f.body);
            --indent_;
            out_ += pad() + "}\n";
            --indent_;
            out_ += pad() + "}\n";
        } else {
            out_ += pad() + "for (auto&& " + f.var + " : (" + expr(*f.iterable) + ")) {\n";
            ++indent_;
            emit_body(*f.body);
            --indent_;
            out_ += pad() + "}\n";
        }
    }

    // ── 声明 ───────────────────────────────────────────────────────
    std::string param_str(ast::Param const& p, bool with_default)
    {
        std::string res;
        switch (p.mode) {
        case ast::ParamMode::In:      res = "cpp2::in<" + type_str(p.type) + "> " + p.name; break;
        case ast::ParamMode::Inout:
        case ast::ParamMode::Out:     res = type_str(p.type) + "& " + p.name; break;
        case ast::ParamMode::Move:    res = type_str(p.type) + "&& " + p.name; break;
        case ast::ParamMode::Copy:    res = type_str(p.type) + " " + p.name; break;
        case ast::ParamMode::Forward: res = std::string("auto&& ") + p.name; break;
        }
        if (with_default && p.default_value) res += " = " + expr(*p.default_value);
        return res;
    }

    std::string params_str(std::vector<ast::Param> const& ps, bool with_defaults)
    {
        std::string s;
        for (size_t i = 0; i < ps.size(); ++i) {
            if (i) s += ", ";
            s += param_str(ps[i], with_defaults);
        }
        return s;
    }

    std::string signature(ast::FuncDecl& f, bool with_defaults)
    {
        std::string s;
        if (f.name == "main") s = "int main(";        // main 恒为 int main(M2b:无参数形态)
        else                  s = "auto " + f.name + "(";
        s += params_str(f.params, with_defaults) + ")";
        if (f.name != "main" && f.ret) s += " -> " + type_str(*f.ret);
        return s;
    }

    // 函数体共用:块体或简短体
    void emit_body_of(bool has_block, ast::Stmt* block, ast::Expr* body_expr,
                      std::optional<ast::TypeUse> const& ret, int line)
    {
        ++indent_;
        if (has_block && block) {
            emit_body(*block);
        } else if (body_expr) {
            bool returns = ret.has_value() && type_str(*ret) != "void";
            sync_line(line);
            out_ += pad() + (returns ? "return " : "(void)(")
                  + expr(*body_expr) + (returns ? ";\n" : ");\n");
        }
        --indent_;
    }

    void emit_prototype(ast::FuncDecl& f)
    {
        sync_line(f.line);
        out_ += signature(f, /*with_defaults*/true) + ";\n";
    }

    void emit_definition(ast::FuncDecl& f)
    {
        sync_line(f.line);
        out_ += signature(f, /*with_defaults*/false) + "\n{\n";
        emit_body_of(f.has_block_body, f.block_body.get(), f.expr_body.get(), f.ret, f.line);
        out_ += "}\n\n";
    }

    void emit_global(ast::GlobalVar& g)
    {
        sync_line(g.line);
        std::string type = g.has_type ? type_str(g.type)
                          : (g.is_const ? "auto const" : "auto");
        out_ += type + " " + g.name
              + (g.init ? " = " + expr(*g.init) : "") + ";\n";
    }

    // ── 枚举与类型 ─────────────────────────────────────────────────
    void emit_enum(ast::EnumDecl& e)
    {
        sync_line(e.line);
        out_ += "enum class " + e.name;
        if (e.underlying) out_ += " : " + type_str(*e.underlying);
        out_ += " { ";
        for (size_t i = 0; i < e.members.size(); ++i) {
            if (i) out_ += ", ";
            out_ += e.members[i];
        }
        out_ += " };\n";
    }

    void emit_struct(ast::StructDecl& s)
    {
        sync_line(s.line);
        out_ += "struct " + s.name;
        if (s.base) out_ += " : public " + type_str(*s.base);
        out_ += " {\n";
        ++indent_;
        for (auto& f : s.fields) {
            sync_line(f.line);
            std::string t = type_str(f.type);
            out_ += pad() + t + " " + f.name + " = " + expr(*f.init) + ";\n";
        }
        --indent_;
        for (auto& md : s.methods) emit_method(s, md);
        out_ += "};\n";
    }

    void emit_method(ast::StructDecl& s, ast::MethodDecl& md)
    {
        sync_line(md.line);
        out_ += "\n";
        if (md.name == "destructor") {
            out_ += pad() + "~" + s.name + "()\n{\n";
            emit_body_of(md.has_block_body, md.block_body.get(), md.expr_body.get(),
                         std::nullopt, md.line);
            out_ += pad() + "}\n";
            return;
        }
        std::string sig = "auto " + md.name + "(" + params_str(md.params, false) + ")";
        if (!md.uses_members) sig = "static " + sig;      // 不引用成员 → 静态(如工厂)
        else if (!md.mutates) sig += " const";            // 默认 self 只读
        if (md.ret) sig += " -> " + type_str(*md.ret);
        out_ += pad() + sig + "\n" + pad() + "{\n";
        emit_body_of(md.has_block_body, md.block_body.get(), md.expr_body.get(), md.ret, md.line);
        out_ += pad() + "}\n";
    }
};

} // namespace

std::string emit_translation_unit(ast::Module& m, sema::Result const& sema,
                                  std::string const& source_name)
{
    return Emitter(m, sema, source_name).run();
}

} // namespace cpp2::emit
